from queue import Full


{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "4f36417f",
   "metadata": {},
   "source": [
    "<h4 align=\"center\" style=\"height:1123px;font-family: 'Times New Roman'\"><b>\n",
    "\n",
    "    LAPORAN PRAKTIKUM\n",
    "\n",
    "    ALGORITMA & PEMOGRAMAN\n",
    "\n",
    "    “OPERATOR PADA PYTHON”\n",
    "\n",
    "    Disusun Oleh :\n",
    "\n",
    "    Varren Della\n",
    "\n",
    "    2611531020\n",
    "\n",
    "    Dosen Pengampu:\n",
    "\n",
    "    Wahyudi.DR.. S.T.M.T\n",
    "\n",
    "    Asisten Praktikum:\n",
    "\n",
    "    Muhammad Galid Alvero\n",
    "\n",
    "<br>\n",
    "\n",
    " <img src=\"image/logo_unand.png\" width=\"200\">\n",
    "\n",
    "<br>\n",
    "\n",
    "    FAKULTAS TEKNOLOGI INFORMASI\n",
    "\n",
    "    DEPARTEMEN INFORMATIKA\n",
    "\n",
    "    UNIVERSITAS ANDALAS\n",
    "\n",
    "    2026\n",
    "\n",
    "</b></h4>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4e92b24",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "<h2 align=\"center\">KATA PENGANTAR</h2>\n",
    "Puji syukur kehadirat Tuhan Yang Maha Esa karena atas rahmat dan karunia-Nya laporan praktikum yang berjudul “Operasi pada Python” ini dapat diselesaikan dengan baik. Laporan ini disusun untuk memenuhi salah satu tugas praktikum serta membantu memahami penggunaan berbagai operasi dalam bahasa pemrograman Python.\n",
    "\n",
    "Dalam praktikum ini, penulis mempelajari beberapa jenis operasi yang terdapat pada Python, seperti operasi aritmatika, perbandingan, logika, penugasan, serta operasi lainnya yang dapat digunakan dalam pembuatan program. Dengan adanya praktikum ini, diharapkan penulis dapat memahami cara kerja operator dan menerapkannya dalam program sederhana.\n",
    "\n",
    "Penulis menyadari bahwa laporan ini masih memiliki kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan agar laporan berikutnya dapat menjadi lebih baik. Semoga laporan ini dapat memberikan manfaat bagi penulis maupun pembaca dalam mempelajari dasar-dasar pemrograman Python.\n",
    "\n",
    "\n",
    "<div align=\"right\" style=\"margin-left:-30px;\">\n",
    "Padang, 2026\n",
    "<br>\n",
    "<br>\n",
    "<br>\n",
    "<br>\n",
    "<br>\n",
    "Varren Della\n",
    "<br>\n",
    "2611531020\n",
    "</div>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "de594eee",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB I<br>PENDAHULUAN</h1>\n",
    "\n",
    "## 1.1 Latar Belakang\n",
    "Python merupakan salah satu bahasa pemrograman tingkat tinggi yang banyak digunakan dalam berbagai bidang, seperti pengembangan web, analisis data, kecerdasan buatan, dan automasi. Salah satu keunggulan Python adalah sintaksnya yang relatif sederhana dan mudah dipahami, sehingga cocok sebagai bahasa pemrograman pertama bagi mahasiswa yang baru belajar pemrograman.Dalam pemrograman, operator memegang peranan penting karena digunakan untuk melakukan operasi terhadap nilai dan variabel, seperti operasi aritmetika, perbandingan, logika, penugasan, dan lain-lain. Pemahaman yang baik mengenai jenis-jenis operator serta cara kerjanya merupakan dasar yang wajib dikuasai sebelum mahasiswa mampu menyusun program yang lebih kompleks.Melalui praktikum ini, mahasiswa diperkenalkan pada berbagai jenis operator dalam Python, fungsi masing-masing operator, serta cara menggunakannya dalam program sederhana. Dengan demikian, praktikum ini diharapkan dapat memperkuat pemahaman dasar pemrograman Python dan menjadi landasan untuk mempelajari topik pemrograman yang lebih lanjut\n",
    "\n",
    "Oleh karena itu, praktikum mengenai operasi pada Python dilakukan agar mahasiswa dapat memahami fungsi dan penggunaan berbagai operator serta mampu menerapkannya dalam program sederhana.\n",
    "\n",
    "## 1.2 Tujuan\n",
    "1. Mengenal berbagai jenis operator yang tersedia dalam bahasa pemrograman Python.\n",
    "2. Memahami fungsi dan kegunaan masing-masing operator pada Python.\n",
    "3. Mampu menerapkan operator tersebut dalam pembuatan program sederhana.\n",
    "4. Mengetahui hasil (output) dari setiap operasi yang dilakukan menggunakan operator Python.\n",
    "\n",
    "## 1.3 Manfaat\n",
    "1. Memperkuat pemahaman mahasiswa mengenai dasar-dasar bahasa pemrograman Python.\n",
    "2. Membantu mahasiswa memahami cara penggunaan berbagai operator dalam Python.\n",
    "3. Melatih kemampuan mahasiswa dalam membuat program sederhana menggunakan Python.\n",
    "4. Menjadi landasan untuk mempelajari konsep pemrograman yang lebih kompleks di tahap selanjutnya.\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b3fea9ae",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB II<br>PEMBAHASAN</h1>\n",
    "\n",
    "## 2.1 Dasar Teori\n",
    "Python memiliki berbagai jenis operator yang digunakan untuk melakukan proses tertentu terhadap data dan variabel. Penggunaan operator menjadi salah satu dasar penting dalam pemrograman karena hampir setiap program membutuhkan operasi terhadap data.\n",
    "\n",
    "1. Operator Aritmatika\n",
    "Operator adalah simbol atau kata kunci khusus dalam bahasa pemrograman yang digunakan untuk melakukan operasi tertentu terhadap satu atau lebih operand (nilai atau variabel). Dalam Python, operator digunakan untuk melakukan berbagai jenis operasi, seperti perhitungan matematika, perbandingan nilai, operasi logika, manipulasi bit, dan penugasan nilai Operator aritmatika digunakan untuk melakukan operasi perhitungan matematika pada Python. Operator yang termasuk di dalamnya adalah penjumlahan (+), pengurangan (-), perkalian (*), pembagian (/), pembagian bulat (//), modulus atau sisa pembagian (%), dan perpangkatan (**). Operator aritmatika dapat digunakan pada berbagai tipe data numerik, seperti integer dan float. Penggunaannya banyak ditemukan dalam perhitungan nilai, transaksi, luas bangun, dan berbagai proses perhitungan lainnya.\n",
    "2. Operator Perbandingan\n",
    "Operator perbandingan digunakan untuk membandingkan dua nilai atau lebih. Hasil dari operasi perbandingan berupa nilai Boolean, yaitu True atau False. Operator yang digunakan meliputi sama dengan (==), tidak sama dengan (!=), lebih besar (>), lebih kecil (<), lebih besar atau sama dengan (>=), serta lebih kecil atau sama dengan (<=). Operator ini biasanya digunakan dalam percabangan dan pemeriksaan kondisi pada suatu program.\n",
    "3. Operator Logika\n",
    "Operator logika digunakan untuk menggabungkan atau memanipulasi beberapa kondisi. Python memiliki tiga operator logika utama, yaitu and, or, dan not. Operator and menghasilkan nilai benar apabila semua kondisi yang diperiksa bernilai benar, sedangkan or menghasilkan nilai benar apabila terdapat setidaknya satu kondisi yang benar. Sementara itu, not digunakan untuk membalik nilai Boolean dari suatu kondisi. Operator logika banyak digunakan dalam proses pengambilan keputusan pada program.\n",
    "4. Operator Penugasan\n",
    "Operator penugasan digunakan untuk memberikan nilai kepada variabel atau mengubah nilai yang telah tersimpan di dalam variabel. Operator yang paling dasar adalah =, sedangkan operator gabungan lainnya antara lain +=, -=, *=, /=, //=, %= dan **=. Operator tersebut dapat membuat penulisan program menjadi lebih sederhana, terutama ketika suatu variabel perlu diperbarui berdasarkan nilai sebelumnya.\n",
    "5. Operator Bitwise\n",
    "Operator bitwise digunakan untuk melakukan operasi pada tingkat bit dari suatu bilangan integer. Python menyediakan beberapa operator bitwise, yaitu AND (&), OR (|), XOR (^), NOT (~), left shift (<<), dan right shift (>>). Operasi ini bekerja dengan memproses representasi biner dari suatu bilangan. Operator bitwise biasanya digunakan dalam pengolahan data tingkat rendah, manipulasi bit, sistem komputer, dan beberapa kebutuhan pemrograman tertentu.\n",
    "6. Operator Keanggotaan\n",
    "Operator keanggotaan digunakan untuk memeriksa apakah suatu nilai terdapat di dalam sebuah objek seperti string, list, tuple, atau set. Python memiliki operator in dan not in. Operator in menghasilkan True apabila suatu nilai ditemukan di dalam objek, sedangkan not in menghasilkan True apabila nilai tersebut tidak ditemukan. Operator ini dapat digunakan untuk melakukan pemeriksaan data dengan cara yang sederhana.\n",
    "7. Operator Identitas\n",
    "Operator identitas digunakan untuk mengetahui apakah dua variabel mengacu pada objek yang sama di dalam memori. Python menyediakan operator is dan is not. Operator is menghasilkan True apabila kedua variabel mengacu pada objek yang sama, sedangkan is not menghasilkan True apabila keduanya tidak mengacu pada objek yang sama. Operator identitas berbeda dengan operator == yang digunakan untuk membandingkan nilai.\n",
    "\n",
    "## 2.2 Kode Program\n",
    "\n",
    "### 2.2.1 Program aritmatika_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7192b9ac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Operator Penjumlahan\n",
      "Hasil = 30\n",
      "\n",
      "Operator Pengurangan\n",
      "Hasil = -10\n",
      "\n",
      "Operator Perkalian\n",
      "Hasil = 200\n",
      "\n",
      "Operator Pembagian\n",
      "Hasil = 0.5\n",
      "\n",
      "Operator Pembagian Bulat\n",
      "Hasil = 0\n",
      "\n",
      "Operator Sisa Bagi\n",
      "Hasil = 10\n",
      "\n",
      "Operator Pangkat\n",
      "Hasil = 100000000000000000000\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama aritmatika_NIM.py\n",
    "# Buat program untuk operator aritmatika dalam Python\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: angka1_1234\n",
    "# Program ini menngunakan fungsi input()\n",
    "# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer\n",
    "\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))\n",
    "\n",
    "# Penjumlahan\n",
    "hasil_1020 = angka1_1020 + angka2_1020\n",
    "print(\"\\nOperator Penjumlahan\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Pengurangan\n",
    "hasil_1020 = angka1_1020 - angka2_1020\n",
    "print(\"\\nOperator Pengurangan\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Perkalian\n",
    "hasil_1020 = angka1_1020 * angka2_1020\n",
    "print(\"\\nOperator Perkalian\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Pembagian, pembagian bulat, dan sisa bagi\n",
    "if angka2_1020 != 0:\n",
    "    hasil_1020 = angka1_1020 / angka2_1020\n",
    "    print(\"\\nOperator Pembagian\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "    hasil_1020 = angka1_1020 // angka2_1020\n",
    "    print(\"\\nOperator Pembagian Bulat\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "    hasil_1020 = angka1_1020 % angka2_1020\n",
    "    print(\"\\nOperator Sisa Bagi\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "else:\n",
    "    print(\"Angka kedua tidak boleh bernilai 0.\")\n",
    "\n",
    "# Pangkat\n",
    "hasil_1020 = angka1_1020 ** angka2_1020\n",
    "print(\"\\nOperator Pangkat\")\n",
    "print(\"Hasil =\",hasil_1020)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f504507",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Membuat input angka<br>\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))<br>\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))<br>\n",
    "Program meminta pengguna memasukkan dua angka. Fungsi input() digunakan untuk menerima data, sedangkan int() mengubah data yang dimasukkan menjadi tipe integer.\n",
    "2. Operator Penjumlahan<br>\n",
    "hasil_1020 = angka1_1020 + angka2_1020<br>\n",
    "Operator + digunakan untuk menjumlahkan angka1_1020 dengan angka2_1020, kemudian hasilnya disimpan ke variabel hasil_1020.\n",
    "3. Operator Pengurangan<br>\n",
    "hasil_1020 = angka1_1020 - angka2_1020-<br>\n",
    "Operator - digunakan untuk mengurangi nilai angka1_1020 dengan angka2_1020.\n",
    "4. Operator Perkalian<br>\n",
    "hasil_1020 = angka1_1020 * angka2_1020<br>\n",
    "Operator * digunakan untuk mengalikan kedua angka yang telah dimasukkan.\n",
    "5. Operator Pembagian<br>\n",
    "hasil_1020 = angka1_1020 / angka2_1020<br>\n",
    "Operator / digunakan untuk melakukan pembagian. Hasil pembagian biasanya berupa tipe data float.\n",
    "6. Operator Pembagian Bulat<br>\n",
    "hasil_1020 = angka1_1020 // angka2_1020<br>\n",
    "Operator // digunakan untuk melakukan pembagian dan mengambil hasil bilangan bulatnya saja, tanpa bagian desimal.\n",
    "7. Operator Sisa Bagi<br>\n",
    "hasil_1020 = angka1_1020 % angka2_1020<br>\n",
    "Operator % digunakan untuk mendapatkan sisa dari hasil pembagian antara angka1_1020 dan angka2_1020.\n",
    "8. Pengecekan angka kedua<br>\n",
    "if angka2_1020 != 0:<br>\n",
    "Program memeriksa apakah angka kedua tidak bernilai 0. Hal ini dilakukan karena pembagian dengan angka 0 tidak diperbolehkan.<br>\n",
    "Jika angka2_1020 bernilai 0, program menjalankan:<br>\n",
    "print(\"Angka kedua tidak boleh bernilai 0.\")\n",
    "9. Operator Pangkat<br>\n",
    "hasil_1020 = angka1_1020 ** angka2_1020<br>\n",
    "Operator ** digunakan untuk menghitung pangkat, yaitu angka1_1020 dipangkatkan dengan angka2_1020.\n",
    "\n",
    "\n",
    "### 2.2.2 Program assigment_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0ee700f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Nilai awal angka1 = 10\n",
      "Nilai angka2 = 20\n",
      "\n",
      "Assigment biasa (=)\n",
      "Hasil = 10\n",
      "\n",
      "Assigment penambahan (+=)\n",
      "Hasil = 30\n",
      "\n",
      "Assigment pengurangan (-=)\n",
      "Hasil = -10\n",
      "\n",
      "Assigment perkalian (*=)\n",
      "Hasil = 200\n",
      "\n",
      "Assigment pembagian (/=)\n",
      "Hasil = 0.5\n",
      "\n",
      "Assigment pembagian bulat (//=)\n",
      "Hasil = 0\n",
      "\n",
      "Operator sisa bagi (%=)\n",
      "Hasil = 10\n",
      "\n",
      "Operator perpangkatan (**=)\n",
      "Hasil = 100000000000000000000\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama assigment_NIM.py\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: angka1_1234\n",
    "# Program ini menngunakan fungsi input()\n",
    "# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer\n",
    "# Program operator assigment dalam Python\n",
    "\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))\n",
    "\n",
    "print(\"\\nNilai awal angka1 =\",angka1_1020)\n",
    "print(\"Nilai angka2 =\",angka2_1020)\n",
    "\n",
    "# Assigment biasa\n",
    "hasil_1020 = angka1_1020 \n",
    "print(\"\\nAssigment biasa (=)\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Assigment penambahan\n",
    "hasil_1020 = angka1_1020 \n",
    "hasil_1020 += angka2_1020 \n",
    "print(\"\\nAssigment penambahan (+=)\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Assigment pengurangan\n",
    "hasil_1020 = angka1_1020 \n",
    "hasil_1020 -= angka2_1020 \n",
    "print(\"\\nAssigment pengurangan (-=)\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Assigment perkalian\n",
    "hasil_1020 = angka1_1020 \n",
    "hasil_1020 *= angka2_1020\n",
    "print(\"\\nAssigment perkalian (*=)\")\n",
    "print(\"Hasil =\",hasil_1020)\n",
    "\n",
    "# Assigment pembagian, pembagian bulat, dan sisa bagi\n",
    "if angka2_1020 != 0:\n",
    "    hasil_1020 = angka1_1020 \n",
    "    hasil_1020 /= angka2_1020\n",
    "    print(\"\\nAssigment pembagian (/=)\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "    # Operator tambahan\n",
    "    hasil_1020 = angka1_1020 \n",
    "    hasil_1020 //= angka2_1020\n",
    "    print(\"\\nAssigment pembagian bulat (//=)\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "    hasil_1020 = angka1_1020 \n",
    "    hasil_1020 %= angka2_1020\n",
    "    print(\"\\nOperator sisa bagi (%=)\")\n",
    "    print(\"Hasil =\",hasil_1020)\n",
    "else:\n",
    "    print(\"\\nPembagian tidak dapat dilakukan.\")\n",
    "    print(\"Angka kedua tidak boleh bernilai 0.\")\n",
    "\n",
    "# Operator tambahan: assigment perpangkatan\n",
    "hasil_1020 = angka1_1020 \n",
    "hasil_1020 **= angka2_1020\n",
    "print(\"\\nOperator perpangkatan (**=)\")\n",
    "print(\"Hasil =\",hasil_1020)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dc345e00",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Membuat input angka<br>\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))<br>\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))<br>\n",
    "Program meminta pengguna memasukkan dua angka. Fungsi input() digunakan untuk menerima masukan, sedangkan int() mengubah masukan tersebut menjadi tipe data integer.\n",
    "2. Menampilkan nilai awal<br>\n",
    "print(\"\\nNilai awal angka1 =\", angka1_1020)<br>\n",
    "print(\"Nilai angka2 =\", angka2_1020)<br>\n",
    "Bagian ini digunakan untuk menampilkan nilai awal dari angka1_1020 dan angka2_1020.\n",
    "3. Assignment biasa (=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "Operator = digunakan untuk memberikan atau menetapkan nilai dari angka1_1020 ke variabel hasil_1020.\n",
    "4. Assignment penambahan (+=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 += angka2_1020<br>\n",
    "Operator += digunakan untuk menambahkan nilai angka2_1020 ke hasil_1020.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 + angka2_1020\n",
    "5. Assignment pengurangan (-=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 -= angka2_1020<br>\n",
    "Operator -= digunakan untuk mengurangi hasil_1020 dengan nilai angka2_1020.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 - angka2_1020\n",
    "6. Assignment perkalian (*=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 *= angka2_1020<br>\n",
    "Operator *= digunakan untuk mengalikan hasil_1020 dengan angka2_1020.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 * angka2_1020\n",
    "7. Assignment pembagian (/=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 /= angka2_1020<br>\n",
    "Operator /= digunakan untuk membagi nilai hasil_1020 dengan angka2_1020.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 / angka2_1020<br>\n",
    "Hasil pembagian menggunakan / biasanya berupa float.\n",
    "8. Assignment pembagian bulat (//=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 //= angka2_1020<br>\n",
    "Operator //= digunakan untuk melakukan pembagian bulat.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 // angka2_1020\n",
    "9. Assignment sisa bagi (%=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 %= angka2_1020<br>\n",
    "Operator %= digunakan untuk mendapatkan sisa hasil pembagian.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 % angka2_1020\n",
    "10. Pengecekan nilai 0<br>\n",
    "if angka2_1020 != 0:<br>\n",
    "Program memeriksa apakah angka2_1020 tidak sama dengan 0. Pemeriksaan ini diperlukan karena operasi pembagian, pembagian bulat, dan sisa bagi tidak dapat dilakukan dengan pembagi 0.<br>\n",
    "Jika nilainya 0, program menampilkan:<br>\n",
    "print(\"\\nPembagian tidak dapat dilakukan.\")<br>\n",
    "print(\"Angka kedua tidak boleh bernilai 0.\")\n",
    "11. Assignment perpangkatan (**=)<br>\n",
    "hasil_1020 = angka1_1020<br>\n",
    "hasil_1020 **= angka2_1020<br>\n",
    "Operator **= digunakan untuk melakukan perpangkatan.<br>\n",
    "Bentuk sederhananya:<br>\n",
    "hasil_1020 = hasil_1020 ** angka2_1020\n",
    "### 2.2.3 Program perbandingan_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4df0577a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Operator lebih besar dari\n",
      "angka1 > angka2 = False\n",
      "\n",
      "Operator lebih kecil dari\n",
      "angka1 < angka2 = True\n",
      "\n",
      "Operator lebih besar dari atau sama dengan\n",
      "angka1 >= angka2 = False\n",
      "\n",
      "Operator lebih kecil dari atau sama dengan\n",
      "angka1 <= angka2 = True\n",
      "\n",
      "Operator sama dengan\n",
      "angka1 == angka2 = False\n",
      "\n",
      "Operator tidak sama dengan\n",
      "angka1 != angka2 = True\n",
      "\n",
      "Perbandingan berantai\n",
      "0 < angka1_1020 < 100 = True\n",
      "0 < angka2_1020 < 100 = True\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama perbandingan_NIM.py\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: angka1_1234\n",
    "# Program ini menngunakan fungsi input()\n",
    "# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer\n",
    "# Program operator perbandingan dalam Python\n",
    "\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))\n",
    "\n",
    "# Lebih besar dari\n",
    "hasil_1020 = angka1_1020 > angka2_1020\n",
    "print(\"\\nOperator lebih besar dari\")\n",
    "print(\"angka1 > angka2 =\",hasil_1020)\n",
    "\n",
    "# Lebih kecil dari\n",
    "hasil_1020 = angka1_1020 < angka2_1020\n",
    "print(\"\\nOperator lebih kecil dari\")\n",
    "print(\"angka1 < angka2 =\",hasil_1020)\n",
    "\n",
    "# Lebih besar dari atau sama dengan\n",
    "hasil_1020 = angka1_1020 >= angka2_1020\n",
    "print(\"\\nOperator lebih besar dari atau sama dengan\")\n",
    "print(\"angka1 >= angka2 =\",hasil_1020)\n",
    "\n",
    "# Lebih kecil dari atau sama dengan\n",
    "hasil_1020 = angka1_1020 <= angka2_1020\n",
    "print(\"\\nOperator lebih kecil dari atau sama dengan\")\n",
    "print(\"angka1 <= angka2 =\",hasil_1020)\n",
    "\n",
    "# Sama dengan\n",
    "hasil_1020 = angka1_1020 == angka2_1020\n",
    "print(\"\\nOperator sama dengan\")\n",
    "print(\"angka1 == angka2 =\",hasil_1020)\n",
    "\n",
    "# Tidak sama dengan\n",
    "hasil_1020 = angka1_1020 != angka2_1020\n",
    "print(\"\\nOperator tidak sama dengan\")\n",
    "print(\"angka1 != angka2 =\",hasil_1020)\n",
    "\n",
    "# Tambahan: perbandingan berantai dalam Python\n",
    "hasil_1020 = 0 < angka1_1020 < 100\n",
    "print(\"\\nPerbandingan berantai\")\n",
    "print(\"0 < angka1_1020 < 100 =\",hasil_1020)\n",
    "\n",
    "hasil_1020 = 0 < angka2_1020 < 100\n",
    "print(\"0 < angka2_1020 < 100 =\",hasil_1020)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba3bf198",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Membuat input angka<br>\n",
    "angka1_1020 = int(input(\"Input angka-1: \"))<br>\n",
    "angka2_1020 = int(input(\"Input angka-2: \"))<br>\n",
    "Program meminta pengguna memasukkan dua angka. Fungsi input() digunakan untuk menerima masukan, sedangkan int() mengubah masukan menjadi tipe data integer.\n",
    "2. Operator lebih besar dari (>)<br>\n",
    "hasil_1020 = angka1_1020 > angka2_1020<br>\n",
    "Operator > digunakan untuk mengecek apakah angka1_1020 lebih besar daripada angka2_1020.<br>\n",
    "Hasilnya berupa nilai Boolean, yaitu True atau False.\n",
    "3. Operator lebih kecil dari (<)<br>\n",
    "hasil_1020 = angka1_1020 < angka2_1020<br>\n",
    "Operator < digunakan untuk mengecek apakah angka1_1020 lebih kecil daripada angka2_1020.\n",
    "4. Operator lebih besar dari atau sama dengan (>=)<br>\n",
    "hasil_1020 = angka1_1020 >= angka2_1020<br>\n",
    "Operator >= mengecek apakah angka1_1020 lebih besar atau sama dengan angka2_1020.\n",
    "5. Operator lebih kecil dari atau sama dengan (<=)<br>\n",
    "hasil_1020 = angka1_1020 <= angka2_1020<br>\n",
    "Operator <= mengecek apakah angka1_1020 lebih kecil atau sama dengan angka2_1020.\n",
    "6. Operator sama dengan (==)<br>\n",
    "hasil_1020 = angka1_1020 == angka2_1020<br>\n",
    "Operator == digunakan untuk mengecek apakah kedua angka memiliki nilai yang sama.<br>\n",
    "Perlu dibedakan antara = dan ==.<br>\n",
    "= digunakan untuk memberikan nilai, sedangkan == digunakan untuk membandingkan nilai.\n",
    "7. Operator tidak sama dengan (!=)<br>\n",
    "hasil_1020 = angka1_1020 != angka2_1020<br>\n",
    "Operator != digunakan untuk mengecek apakah angka1_1020 dan angka2_1020 memiliki nilai yang berbeda.\n",
    "8. Perbandingan berantai untuk angka pertama<br>\n",
    "hasil_1020 = 0 < angka1_1020 < 100<br>\n",
    "Kode tersebut merupakan perbandingan berantai (chained comparison). Artinya, program mengecek apakah angka1_1020 berada di antara 0 dan 100, dengan syarat:<br>\n",
    "0 < angka1_1020 dan angka1_1020 < 100<br>\n",
    "Jika kedua kondisi benar, hasilnya True.\n",
    "9. Perbandingan berantai untuk angka kedua<br>\n",
    "hasil_1020 = 0 < angka2_1020 < 100<br>\n",
    "Bagian ini memiliki fungsi yang sama, tetapi digunakan untuk mengecek apakah angka2_1020 berada di antara 0 dan 100.\n",
    "\n",
    "### 2.2.4 Program logika_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0468c84f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "A1 =  True\n",
      "A2 =  False\n",
      "\n",
      "Konjungsi (AND)\n",
      "A1 and A2 = False\n",
      "\n",
      "Disjungsi (OR)\n",
      "A1 or A2 = True\n",
      "\n",
      "Negasi A1(NOT)\n",
      "not A1 False\n",
      "\n",
      "Negasi A2(NOT)\n",
      "not A2 True\n",
      "\n",
      "Disjungsi Ekslusif (XOR)\n",
      "A1 XOR A2 True\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama logika_NIM.py\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: a1_1234\n",
    "# Program ini menngunakan fungsi input()\n",
    "# Program operator logika dalam Python\n",
    "\n",
    "# Memasukan nilai boolean\n",
    "# Input tidak peka terhadap huruf besar dan kecil\n",
    "a1_1020 = input(\"Input nilai boolean-1 (true/false): \").strip().lower() == \"true\"\n",
    "a2_1020 = input(\"Input nilai boolean-2 (true/false): \").strip().lower() == \"true\"\n",
    "\n",
    "print(\"\\nA1 = \",a1_1020)\n",
    "print(\"A2 = \",a2_1020)\n",
    "\n",
    "# Konjungsi: bernilai True jika keduanya True\n",
    "hasil_1020 = a1_1020 and a2_1020\n",
    "print(\"\\nKonjungsi (AND)\")\n",
    "print(\"A1 and A2 =\",hasil_1020)\n",
    "\n",
    "# Disjungsi: bernilai True jika salah satunya False\n",
    "hasil_1020 = a1_1020 or a2_1020\n",
    "print(\"\\nDisjungsi (OR)\")\n",
    "print(\"A1 or A2 =\",hasil_1020)\n",
    "\n",
    "# Negasi A1: membalik nilai A1\n",
    "hasil_1020 = not a1_1020\n",
    "print(\"\\nNegasi A1(NOT)\")\n",
    "print(\"not A1\",hasil_1020)\n",
    "\n",
    "# Negasi A2: membalik nilai A2\n",
    "hasil_1020 = not a2_1020\n",
    "print(\"\\nNegasi A2(NOT)\")\n",
    "print(\"not A2\",hasil_1020)\n",
    "\n",
    "# XOR: bernilai True jika kedua nilai berbeda\n",
    "hasil_1020 = a1_1020 != a2_1020\n",
    "print(\"\\nDisjungsi Ekslusif (XOR)\")\n",
    "print(\"A1 XOR A2\",hasil_1020)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "96da2384",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Memasukkan nilai Boolean<br>\n",
    "a1_1020 = input(\"Input nilai boolean-1 (true/false): \").strip().lower() == \"true\"<br>\n",
    "a2_1020 = input(\"Input nilai boolean-2 (true/false): \").strip().lower() == \"true\"<br>\n",
    "Program meminta pengguna memasukkan nilai true atau false.<br>\n",
    "input() menerima masukan dari pengguna.<br>\n",
    ".strip() menghilangkan spasi di awal dan akhir.<br>\n",
    ".lower() mengubah huruf menjadi huruf kecil sehingga TRUE, True, dan true dapat diproses dengan cara yang sama.<br>\n",
    "== \"true\" membandingkan masukan dengan teks \"true\" dan menghasilkan nilai Boolean True atau False.\n",
    "2. Menampilkan nilai Boolean<br>\n",
    "print(\"\\nA1 = \", a1_1020)<br>\n",
    "print(\"A2 = \", a2_1020)<br>\n",
    "Bagian ini menampilkan nilai Boolean yang telah dimasukkan dan dikonversi oleh program.\n",
    "3. Konjungsi (AND)\n",
    "hasil_1020 = a1_1020 and a2_1020<br>\n",
    "Operator and digunakan untuk menggabungkan dua kondisi. Hasilnya akan True hanya jika kedua nilai bernilai True.<br>\n",
    "Contoh:<br>\n",
    "A1 = True<br>\n",
    "A2 = True<br>\n",
    "Hasil = True<br>\n",
    "Jika salah satu atau keduanya False, hasilnya False.\n",
    "4. Disjungsi (OR)<br>\n",
    "hasil_1020 = a1_1020 or a2_1020<br>\n",
    "Operator or menghasilkan True jika minimal salah satu nilai bernilai True.<br>\n",
    "Hasilnya hanya False jika kedua nilai bernilai False.\n",
    "5. Negasi A1 (NOT)<br>\n",
    "hasil_1020 = not a1_1020<br>\n",
    "Operator not digunakan untuk membalik nilai Boolean dari a1_1020.<br>\n",
    "Jika A1 = True, maka not A1 = False.<br>\n",
    "Jika A1 = False, maka not A1 = True.\n",
    "6. Negasi A2 (NOT)<br>\n",
    "hasil_1020 = not a2_1020<br>\n",
    "Bagian ini memiliki fungsi yang sama dengan sebelumnya, tetapi digunakan untuk membalik nilai Boolean a2_1020.\n",
    "7. Disjungsi Eksklusif (XOR)<br>\n",
    "hasil_1020 = a1_1020 != a2_1020<br>\n",
    "Operator XOR digunakan untuk menghasilkan True jika kedua nilai berbeda.\n",
    "\n",
    "### 2.2.5 Program lainnya_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "105d04ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======================================\n",
      "1. OPERATOR KEANGGOTAAN\n",
      "======================================\n",
      "\n",
      "Operator keanggotaan IN\n",
      "20 in [10, 20, 30, 40, 50] = True\n",
      "\n",
      "Operator keanggotaan NOT IN\n",
      "20 not in [10, 20, 30, 40, 50] = False\n",
      "======================================\n",
      "2. OPERATOR IDENTIAS\n",
      "======================================\n",
      "object1 = [10, 20, 30, 40, 50]\n",
      "object2 = [10, 20, 30, 40, 50]\n",
      "object3 = [10, 20, 30, 40, 50]\n",
      "\n",
      "Operator identitas IS\n",
      "objek1 is objek2 = True\n",
      "\n",
      "Operator identitas IS NOT\n",
      "objek1 is not objek2 = False\n",
      "\n",
      "Perbandingan identitas dan nilai\n",
      "objek1 is objek3 = False\n",
      "objek1 == objek3 = True\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama lainnya_NIM.py\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: angka1_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "# Program operator keanggotaan dan identitas\n",
    "\n",
    "print(\"======================================\")\n",
    "print(\"1. OPERATOR KEANGGOTAAN\")\n",
    "print(\"======================================\")\n",
    "\n",
    "# Input beberapa data yang dipisahkan dengan koma\n",
    "input_data_1020 = input(\"Masukkan beberapa angka, pisahkan dengan koma: \")\n",
    "\n",
    "# Mengubah input menjadi list integer\n",
    "data_1020 = [int(angka.strip()) for angka in input_data_1020.split(',')]\n",
    "\n",
    "nilai_dicari_1020 = int(input(\"Masukkan angka yang ingin dicari: \"))\n",
    "\n",
    "# Operator in\n",
    "hasil_1020 = nilai_dicari_1020 in data_1020\n",
    "print(\"\\nOperator keanggotaan IN\")\n",
    "print(nilai_dicari_1020,\"in\",data_1020,\"=\",hasil_1020)\n",
    "\n",
    "# Operator not in\n",
    "hasil_1020 = nilai_dicari_1020 not in data_1020\n",
    "print(\"\\nOperator keanggotaan NOT IN\")\n",
    "print(nilai_dicari_1020,\"not in\",data_1020,\"=\",hasil_1020)\n",
    "\n",
    "print(\"======================================\")\n",
    "print(\"2. OPERATOR IDENTIAS\")\n",
    "print(\"======================================\")\n",
    "\n",
    "# objek1 menggunakan list dari input perngguna\n",
    "object1_1020 = data_1020\n",
    "\n",
    "# objek2 merujuk pada objek yang sama dengan objek1\n",
    "object2_1020 = object1_1020\n",
    "\n",
    "# objek3 memiliki isi sama, tetapi merupakan objek baru\n",
    "object3_1020 = data_1020.copy()\n",
    "\n",
    "print(\"object1 =\",object1_1020)\n",
    "print(\"object2 =\",object2_1020)\n",
    "print(\"object3 =\",object3_1020)\n",
    "\n",
    "# Operator is\n",
    "hasil_1020 = object1_1020 is object2_1020\n",
    "print(\"\\nOperator identitas IS\")\n",
    "print(\"objek1 is objek2 =\",hasil_1020)\n",
    "\n",
    "# Operator is not\n",
    "hasil_1020 = object1_1020 is not object2_1020\n",
    "print(\"\\nOperator identitas IS NOT\")\n",
    "print(\"objek1 is not objek2 =\",hasil_1020)\n",
    "\n",
    "# Membandingkan identitas dan nilai\n",
    "print(\"\\nPerbandingan identitas dan nilai\")\n",
    "print(\"objek1 is objek3 =\",object1_1020 is object3_1020)\n",
    "print(\"objek1 == objek3 =\",object1_1020 == object3_1020)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "033cda8c",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Menampilkan judul program<br>\n",
    "print(\"======================================\")<br>\n",
    "print(\"1. OPERATOR KEANGGOTAAN\")<br>\n",
    "print(\"======================================\")<br>\n",
    "Digunakan untuk menampilkan judul bagian Operator Keanggotaan agar output program lebih terstruktur.\n",
    "2. Menerima input beberapa angka\n",
    "input_data_1020 = input(\"Masukkan beberapa angka, pisahkan dengan koma: \")<br>\n",
    "Program meminta pengguna memasukkan beberapa angka yang dipisahkan dengan tanda koma. Input tersebut awalnya disimpan sebagai string.<br>\n",
    "Contoh:<br>\n",
    "10, 20, 30, 40\n",
    "3. Mengubah input menjadi list integer<br>\n",
    "data_1020 = [int(angka.strip()) for angka in input_data_1021.split(',')]<br>\n",
    "Kode ini mengubah input string menjadi list yang berisi integer.<br>\n",
    ".split(',') memisahkan data berdasarkan tanda koma.<br>\n",
    ".strip() menghilangkan spasi yang tidak diperlukan.<br>\n",
    "int() mengubah setiap data menjadi integer.<br>\n",
    "[ ... for ... ] digunakan untuk membuat list.<br>\n",
    "Contoh:<br>\n",
    "Input: 10, 20, 30<br>\n",
    "Hasil: [10, 20, 30]\n",
    "4. Memasukkan nilai yang ingin dicari<br>\n",
    "nilai_dicari_1020 = int(input(\"Masukkan angka yang ingin dicari: \"))<br>\n",
    "Program meminta pengguna memasukkan angka yang akan dicari di dalam data_1020. Input dikonversi menjadi tipe data integer.\n",
    "5. Operator keanggotaan in<br>\n",
    "hasil_1020 = nilai_dicari_1020 in data_1020<br>\n",
    "Operator in digunakan untuk mengecek apakah suatu nilai terdapat di dalam sebuah list.<br>\n",
    "Jika nilai ditemukan, hasilnya True. Jika tidak ditemukan, hasilnya False.<br>\n",
    "Contoh:<br>\n",
    "data = [10, 20, 30]<br>\n",
    "20 in data → True<br>\n",
    "50 in data → False\n",
    "6. Operator keanggotaan not in<br>\n",
    "hasil_1020 = nilai_dicari_1020 not in data_1020<br>\n",
    "Operator not in digunakan untuk mengecek apakah suatu nilai tidak terdapat di dalam list.<br>\n",
    "Jika nilai tidak ditemukan, hasilnya True. Jika ditemukan, hasilnya False.\n",
    "7. Menampilkan judul operator identitas<br>\n",
    "print(\"======================================\")<br>\n",
    "print(\"2. OPERATOR IDENTIAS\")<br>\n",
    "print(\"======================================\")<br>\n",
    "Bagian ini menampilkan judul untuk bagian Operator Identitas.\n",
    "8. Membuat object1<br>\n",
    "object1_1020 = data_1020<br>\n",
    "Variabel object1_1020 menunjuk ke objek list yang sama dengan data_1020.\n",
    "9. Membuat object2<br>\n",
    "object2_1020 = object1_1020<br>\n",
    "Variabel object2_1020 menunjuk ke objek yang sama dengan object1_1020.<br>\n",
    "Artinya, object1_1020 dan object2_1020 memiliki identitas objek yang sama.\n",
    "10. Membuat object3<br>\n",
    "object3_1020 = data_1020.copy()<br>\n",
    "copy() membuat objek list baru yang memiliki isi yang sama dengan data_1020.<br>\n",
    "Jadi, nilai object3_1020 sama dengan object1_1020, tetapi objeknya berbeda.\n",
    "11. Menampilkan isi objek<br>\n",
    "print(\"object1 =\",object1_1020)<br>\n",
    "print(\"object2 =\",object2_1020)<br>\n",
    "print(\"object3 =\",object3_1020)<br>\n",
    "Digunakan untuk menampilkan isi dari ketiga objek.<br>\n",
    "Karena ketiganya memiliki isi yang sama, hasil yang ditampilkan akan terlihat sama.\n",
    "12. Operator identitas is<br>\n",
    "hasil_1020 = object1_1020 is object2_1020<br>\n",
    "Operator is digunakan untuk mengecek apakah dua variabel menunjuk ke objek yang sama.<br>\n",
    "Karena object2_1020 dibuat dari object1_1020, hasilnya adalah:<br>\n",
    "True\n",
    "13. Operator identitas is not<br>\n",
    "hasil_1020 = object1_1020 is not object2_1020<br>\n",
    "Operator is not digunakan untuk mengecek apakah dua variabel menunjuk ke objek yang berbeda.<br>\n",
    "Karena object1_1020 dan object2_1020 menunjuk objek yang sama, hasilnya adalah:<br>\n",
    "False\n",
    "14. Membandingkan identitas dan nilai<br>\n",
    "print(\"objek1 is objek3 =\",object1_1020 is object3_1020)<br>\n",
    "print(\"objek1 == objek3 =\",object1_1020 == object3_1020)<br>\n",
    "Baris pertama menggunakan is untuk membandingkan identitas objek. Karena object3_1020 dibuat menggunakan .copy(), objeknya berbeda sehingga hasilnya:<br>\n",
    "False<br>\n",
    "Baris kedua menggunakan == untuk membandingkan nilai atau isi objek. Karena isi object1_1020 dan object3_1020 sama, hasilnya:<br>\n",
    "True\n",
    "\n",
    "### 2.2.6 Program bitwise_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d6efa108",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======================================\n",
      "3. OPERATOR BITWISE\n",
      "======================================\n",
      "\n",
      "Angka dalam bentuk desimal dan biner\n",
      "angka1 = 10 | biner = 0b1010\n",
      "angka1 = 20 | biner = 0b10100\n",
      "\n",
      "Bitwise AND (&)\n",
      "10 & 20 0\n",
      "Biner hasil = 0b0\n",
      "Biner hasil (8 bit) = 00000000\n",
      "\n",
      "Bitwise OR (|)\n",
      "10 | 20 30\n",
      "Biner hasil = 0b11110\n",
      "Biner hasil (8 bit) = 00011110\n",
      "\n",
      "Bitwise XOR (^)\n",
      "10 ^ 20 30\n",
      "Biner hasil = 0b11110\n",
      "Biner hasil (8 bit) = 00011110\n",
      "\n",
      "Bitwise NOT (~)\n",
      "10 ~ 20 -11\n",
      "Biner hasil = -0b1011\n",
      "Biner hasil (8 bit) = -0001011\n",
      "\n",
      "Bitwise geser kiri (<<)\n",
      "10 << 1 = 20\n",
      "Biner hasil = 0b10100\n",
      "Biner hasil (8 bit) = 00010100\n",
      "\n",
      "Bitwise geser kanan (>>)\n",
      "10 >> 1 = 5\n",
      "Biner hasil = 0b101\n",
      "Biner hasil (8 bit) = 00000101\n"
     ]
    }
   ],
   "source": [
    "# Buat file dengan nama bitwise_NIM.py\n",
    "# Nama variabel ditambah 4 digit nim terakhir contoh: angka1_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "\n",
    "print(\"======================================\")\n",
    "print(\"3. OPERATOR BITWISE\")\n",
    "print(\"======================================\")\n",
    "\n",
    "angka1_1020 = int(input(\"Masukkan angka bitwise-1: \"))\n",
    "angka2_1020 = int(input(\"Masukkan angka bitwise-2: \"))\n",
    "\n",
    "print(\"\\nAngka dalam bentuk desimal dan biner\")\n",
    "print(\"angka1 =\",angka1_1020,\"| biner =\",bin(angka1_1020))\n",
    "print(\"angka1 =\",angka2_1020,\"| biner =\",bin(angka2_1020))\n",
    "\n",
    "# Bitwise AND\n",
    "hasil_1020 = angka1_1020 & angka2_1020\n",
    "print(\"\\nBitwise AND (&)\")\n",
    "print(angka1_1020,\"&\",angka2_1020,hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "# Bitwise OR\n",
    "hasil_1020 = angka1_1020 | angka2_1020\n",
    "print(\"\\nBitwise OR (|)\")\n",
    "print(angka1_1020,\"|\",angka2_1020,hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "# Bitwise XOR\n",
    "hasil_1020 = angka1_1020 ^ angka2_1020\n",
    "print(\"\\nBitwise XOR (^)\")\n",
    "print(angka1_1020,\"^\",angka2_1020,hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "# Bitwise NOT\n",
    "hasil_1020 = ~angka1_1020\n",
    "print(\"\\nBitwise NOT (~)\")\n",
    "print(angka1_1020,\"~\",angka2_1020,hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "# Bitwise geser kiri\n",
    "jumlah_geser_1020 = int(input(\"\\nMasukkan jumlah pergeseran bit: \"))\n",
    "\n",
    "hasil_1020 = angka1_1020 << jumlah_geser_1020\n",
    "print(\"\\nBitwise geser kiri (<<)\")\n",
    "print(angka1_1020,\"<<\",jumlah_geser_1020,\"=\",hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "# Bitwise geser kanan\n",
    "hasil_1020 = angka1_1020 >> jumlah_geser_1020\n",
    "print(\"\\nBitwise geser kanan (>>)\")\n",
    "print(angka1_1020,\">>\",jumlah_geser_1020,\"=\",hasil_1020)\n",
    "print(\"Biner hasil =\",bin(hasil_1020))\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "64084288",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Menampilkan judul<br>\n",
    "print(\"======================================\")<br>\n",
    "print(\"3. OPERATOR BITWISE\")<br>\n",
    "print(\"======================================\")<br>\n",
    "Digunakan untuk menampilkan judul bagian program agar output terlihat lebih terstruktur.\n",
    "2. Memasukkan dua angka<br>\n",
    "angka1_1020 = int(input(\"Masukkan angka bitwise-1: \"))<br>\n",
    "angka2_1020 = int(input(\"Masukkan angka bitwise-2: \"))<br>\n",
    "Program meminta pengguna memasukkan dua angka. input() menerima masukan, sedangkan int() mengubah masukan menjadi tipe data integer.\n",
    "3. Menampilkan angka desimal dan biner<br>\n",
    "print(\"\\nAngka dalam bentuk desimal dan biner\")<br>\n",
    "print(\"angka1 =\",angka1_1020,\"| biner =\",bin(angka1_1020))<br>\n",
    "print(\"angka1 =\",angka2_1020,\"| biner =\",bin(angka2_1020))<br>\n",
    "Menampilkan nilai angka dalam bentuk desimal dan biner. Fungsi bin() digunakan untuk mengubah bilangan integer menjadi bentuk biner.\n",
    "4. Operasi AND (&)<br>\n",
    "hasil_1020 = angka1_1020 & angka2_1020<br>\n",
    "Operator & membandingkan setiap bit dari kedua angka. Hasil bit akan 1 jika kedua bit bernilai 1.<br>\n",
    "print(angka1_1020,\"&\",angka2_1020,hasil_1020)<br>\n",
    "print(\"Biner hasil =\",bin(hasil_1020))<br>\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))<br>\n",
    "Menampilkan hasil dalam bentuk desimal, biner biasa, dan biner dengan panjang 8 bit. format(..., \"08b\") digunakan untuk menampilkan biner minimal 8 digit.\n",
    "5. Operasi OR (|)<br>\n",
    "hasil_1020 = angka1_1020 | angka2_1020<br>\n",
    "Operator | menghasilkan bit 1 jika salah satu atau kedua bit bernilai 1.<br>\n",
    "print(angka1_1020,\"|\",angka2_1020,hasil_1020)<br>\n",
    "print(\"Biner hasil =\",bin(hasil_1020))<br>\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))<br>\n",
    "Menampilkan hasil operasi dalam bentuk desimal dan biner.\n",
    "6. Operasi XOR (^)<br>\n",
    "hasil_1020 = angka1_1020 ^ angka2_1020<br>\n",
    "Operator ^ menghasilkan bit 1 jika kedua bit berbeda.<br>\n",
    "Contoh:<br>\n",
    "0 ^ 0 = 0<br>\n",
    "0 ^ 1 = 1<br>\n",
    "1 ^ 0 = 1<br>\n",
    "1 ^ 1 = 0<br>\n",
    "Bagian print() berikutnya menampilkan hasil dalam bentuk desimal dan biner.\n",
    "7. Operasi NOT (~)<br>\n",
    "hasil_1020 = ~angka1_1020<br>\n",
    "Operator ~ digunakan untuk membalik bit dari angka1_1020. Bit 1 menjadi 0 dan bit 0 menjadi 1.<br>\n",
    "print(angka1_1020,\"~\",angka2_1020,hasil_1020)<br>\n",
    "Menampilkan hasil operasi NOT.<br>\n",
    "Namun, pada baris tersebut angka2_1020 ikut ditampilkan meskipun operasi NOT hanya dilakukan terhadap angka1_1020. Jika ingin output lebih sesuai, sebaiknya:<br>\n",
    "print(\"~\", angka1_1020, \"=\", hasil_1020)\n",
    "8. Memasukkan jumlah pergeseran bit<br>\n",
    "jumlah_geser_1020 = int(input(\"\\nMasukkan jumlah pergeseran bit: \"))<br>\n",
    "Program meminta jumlah posisi bit yang ingin digeser. Nilai tersebut dikonversi menjadi integer.\n",
    "9. Pergeseran bit ke kiri (<<)<br>\n",
    "hasil_1020 = angka1_1020 << jumlah_geser_1020<br>\n",
    "Operator << menggeser bit angka1_1020 ke sebelah kiri sebanyak jumlah_geser_1020 posisi.<br>\n",
    "Secara sederhana, pergeseran kiri satu posisi biasanya sama dengan mengalikan bilangan dengan 2.<br>\n",
    "Contoh:<br>\n",
    "5 = 0101<br>\n",
    "5 << 1 = 1010 = 10\n",
    "10. Menampilkan hasil geser kiri<br>\n",
    "print(\"\\nBitwise geser kiri (<<)\")<br>\n",
    "print(angka1_1020,\"<<\",jumlah_geser_1020,\"=\",hasil_1020)<br>\n",
    "print(\"Biner hasil =\",bin(hasil_1020))<br>\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))<br>\n",
    "Menampilkan hasil pergeseran dalam bentuk desimal, biner, dan biner 8 bit.\n",
    "11. Pergeseran bit ke kanan (>>)<br>\n",
    "hasil_1020 = angka1_1020 >> jumlah_geser_1020<br>\n",
    "Operator >> menggeser bit angka1_1020 ke sebelah kanan sebanyak jumlah posisi yang ditentukan.<br>\n",
    "Secara sederhana, untuk bilangan positif, pergeseran kanan satu posisi biasanya sama dengan membagi bilangan dengan 2 dan mengambil bagian bulatnya.<br>\n",
    "Contoh:<br>\n",
    "10 = 1010<br>\n",
    "10 >> 1 = 0101 = 5\n",
    "12. Menampilkan hasil geser kanan<br>\n",
    "print(\"\\nBitwise geser kiri (>>)\")<br>\n",
    "print(angka1_1020,\">>\",jumlah_geser_1020,\"=\",hasil_1020)<br>\n",
    "print(\"Biner hasil =\",bin(hasil_1020))<br>\n",
    "print(\"Biner hasil (8 bit) =\",format(hasil_1020,\"08b\"))\n",
    "\n",
    "---\n",
    "## Tugas Praktikum\n",
    "\n",
    "**Soal :**\n",
    "\n",
    "<div align=\"center\">\n",
    "<img src=\"image/soal_tugas.png\" width=\"500\"><br>\n",
    "<em>Gambar 2.2 : Soal Tugas Praktikum</em>\n",
    "</div>\n",
    "\n",
    "**Kode Jawaban :**\n",
    "\n",
    "a. Kode Program tugas3_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": Full,
   "id": "3288b6ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== SISTEM TRANSAKSI TOKO ===\n",
      "\n",
      "=== DATA TRANSAKSI ===\n",
      "Nama Pelanggan       : adib\n",
      "Status Pelanggan     : member\n",
      "Total Belanja        : Rp250000\n",
      "Jumlah Barang        : 4\n",
      "Kode Promo           : HEMAT10\n",
      "\n",
      "=== HASIL VALIDASI ===\n",
      "Belanja >= Rp200000        : True\n",
      "Jumlah Barang >= 3         : True\n",
      "Status Member              : True\n",
      "Kode Promo Tersedia        : True\n",
      "Mendapatkan Diskon         : True\n",
      "Mendapatkan Promo          : True\n",
      "\n",
      "=== HASIL PERHITUNGAN ===\n",
      "Diskon                      : Rp12500.0\n",
      "Total Pembayaran            : Rp237500.0\n",
      "Rata-rata Harga Barang      : Rp59375.0\n",
      "\n",
      "=== HAK AKSES PELANGGAN ===\n",
      "Kode Hak Akses              : ...\n",
      "Member Access               : True\n",
      "Promo Access                : True\n",
      "Free Shipping Access        : ...\n",
      "\n",
      "=== OPERASI BITWISE ===\n",
      "=== Kode Status Transaksi ===\n",
      "0001 | 0010 | 0100 | 1000\n",
      "Kode Biner   : 1111\n",
      "Kode Desimal : 15\n",
      "\n",
      "=== Pemeriksaan Status ===\n",
      "Cek Member\n",
      "1111 & 0001\n",
      "Hasil Biner   : 0001\n",
      "Hasil Desimal : 1\n",
      "Cek Promo\n",
      "1111 & 1000\n",
      "Hasil Biner   : 1000\n",
      "Hasil Desimal : 8\n",
      "\n",
      "=== Perbandingan Status ===\n",
      "Kode Transaksi : 1111\n",
      "Kode Referensi : 1011\n",
      "1111 ^ 1011\n",
      "Hasil Biner   : 0100\n",
      "Hasil Desimal : 4\n",
      "\n",
      "=== Shift ===\n",
      "1111 << 1\n",
      "Hasil Biner   : 11110\n",
      "Hasil Desimal : 30\n",
      "=== SELESAI ===\n"
     ]
    }
   ],
   "source": [
    "print(\"=== SISTEM TRANSAKSI TOKO ===\")\n",
    "nama_1020 = input(\"Masukkan Nama Pelanggan : \")\n",
    "status_1020 = input(\"Masukkan Status Pelanggan (member/nonmember) : \")\n",
    "total_1020 = int(input(\"Masukkan Total Belanja : \"))\n",
    "jumlah_1020 = int(input(\"Masukkan Jumlah Barang : \"))\n",
    "promo_1020 = input(\"Masukkan Kode Promo : \")\n",
    "\n",
    "print(\"\\n=== DATA TRANSAKSI ===\")\n",
    "print(f\"Nama Pelanggan       : {nama_1020}\")\n",
    "print(f\"Status Pelanggan     : {status_1020}\")\n",
    "print(f\"Total Belanja        : Rp{total_1020}\")\n",
    "print(f\"Jumlah Barang        : {jumlah_1020}\")\n",
    "print(f\"Kode Promo           : {promo_1020}\")\n",
    "\n",
    "kode_promo_1020 = [\"HEMAT10\", \"HEMAT20\", \"HIDUPMAHASISWA\", \"HIDUPFTI\"] #list kode promo\n",
    "\n",
    "syarat_total_1020 = total_1020 >= 200000 # apakah memenuhi syarat belanja\n",
    "syarat_jumlah_1020 = jumlah_1020 >= 3 # apakah memenuhi syarat barang\n",
    "status_valid_1020 = status_1020 == \"member\" # apakah user member\n",
    "promo_valid_1020 = promo_1020 in kode_promo_1020 # apakah kode promo ada dalam list\n",
    "\n",
    "print(\"\\n=== HASIL VALIDASI ===\")\n",
    "print(f\"Belanja >= Rp200000        : {syarat_total_1020}\")\n",
    "print(f\"Jumlah Barang >= 3         : {syarat_jumlah_1020}\")\n",
    "print(f\"Status Member              : {status_valid_1020}\")\n",
    "print(f\"Kode Promo Tersedia        : {promo_valid_1020}\")\n",
    "print(f\"Mendapatkan Diskon         : {syarat_jumlah_1020 or syarat_total_1020}\")\n",
    "print(f\"Mendapatkan Promo          : {promo_valid_1020}\")\n",
    "\n",
    "diskon_1020 = 0.05\n",
    "\n",
    "print(\"\\n=== HASIL PERHITUNGAN ===\")\n",
    "print(f\"Diskon                      : Rp{diskon_1020 * total_1020}\")\n",
    "print(f\"Total Pembayaran            : Rp{total_1020 - total_1020 * diskon_1020}\")\n",
    "print(f\"Rata-rata Harga Barang      : Rp{(total_1020 - total_1020 * diskon_1020)/jumlah_1020}\")\n",
    "\n",
    "print(\"\\n=== HAK AKSES PELANGGAN ===\")\n",
    "print(f\"Kode Hak Akses              : ...\")\n",
    "print(f\"Member Access               : {status_valid_1020}\")\n",
    "print(f\"Promo Access                : {promo_valid_1020}\")\n",
    "print(f\"Free Shipping Access        : ...\")\n",
    "\n",
    "kode_transaksi_1020 = int(status_valid_1020) << 0 | int(syarat_total_1020) << 1 | int(syarat_jumlah_1020) << 2 | int(promo_valid_1020) << 3\n",
    "kode_referensi_1020 = int(status_valid_1020) << 0 | int(syarat_total_1020) << 1 | int(promo_valid_1020) << 3\n",
    "\n",
    "print(\"\\n=== OPERASI BITWISE ===\")\n",
    "print(\"=== Kode Status Transaksi ===\")\n",
    "print(f\"{format(int(status_valid_1020) << 0,\"04b\")} | {format(int(syarat_total_1020) << 1,\"04b\")} | {format(int(syarat_jumlah_1020) << 2,\"04b\")} | {format(int(promo_valid_1020) << 3,\"04b\")}\")\n",
    "print(f\"Kode Biner   : {format(kode_transaksi_1020,\"04b\")}\")\n",
    "print(f\"Kode Desimal : {kode_transaksi_1020}\")\n",
    "\n",
    "print(\"\\n=== Pemeriksaan Status ===\")\n",
    "print(\"Cek Member\")\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} & {format(int(status_valid_1020) << 0,\"04b\")}\")\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) & int(status_valid_1020) << 0,\"04b\")}\")\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) & int(status_valid_1020) << 0}\")\n",
    "\n",
    "print(\"Cek Promo\")\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} & {format(int(promo_valid_1020) << 3,\"04b\")}\")\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) & int(promo_valid_1020) << 3,\"04b\")}\")\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) & int(promo_valid_1020) << 3}\")\n",
    "\n",
    "print(\"\\n=== Perbandingan Status ===\")\n",
    "print(f\"Kode Transaksi : {format(kode_transaksi_1020,\"04b\")}\")\n",
    "print(f\"Kode Referensi : {format(kode_referensi_1020,\"04b\")}\")\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} ^ {format(kode_referensi_1020,\"04b\")}\")\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) ^ (kode_referensi_1020),\"04b\")}\")\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) ^ (kode_referensi_1020)}\")\n",
    "\n",
    "print(\"\\n=== Shift ===\")\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} << 1\")\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) << 1,\"04b\")}\")\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) << 1}\") \n",
    "print(\"=== SELESAI ===\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4ec191f",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "**Penjelasan :** \n",
    "1. Menampilkan judul program<br>\n",
    "print(\"=== SISTEM TRANSAKSI TOKO ===\")<br>\n",
    "Menampilkan judul utama program.\n",
    "2. Memasukkan data pelanggan<br>\n",
    "nama_1020 = input(\"Masukkan Nama Pelanggan : \")<br>\n",
    "status_1020 = input(\"Masukkan Status Pelanggan (member/nonmember) : \")<br>\n",
    "total_1020 = int(input(\"Masukkan Total Belanja : \"))<br>\n",
    "jumlah_1020 = int(input(\"Masukkan Jumlah Barang : \"))<br>\n",
    "promo_1020 = input(\"Masukkan Kode Promo : \")<br>\n",
    "Program meminta nama, status pelanggan, total belanja, jumlah barang, dan kode promo. int() digunakan untuk mengubah total belanja dan jumlah barang menjadi integer.\n",
    "3. Menampilkan data transaksi<br>\n",
    "print(f\"Nama Pelanggan       : {nama_1020}\")<br>\n",
    "print(f\"Status Pelanggan     : {status_1020}\")<br>\n",
    "print(f\"Total Belanja        : Rp{total_1020}\")<br>\n",
    "print(f\"Jumlah Barang        : {jumlah_1020}\")<br>\n",
    "print(f\"Kode Promo           : {promo_1020}\")<br>\n",
    "Menampilkan kembali data yang telah dimasukkan. f-string digunakan agar nilai variabel dapat langsung dimasukkan ke dalam teks.\n",
    "4. Menentukan kode promo yang tersedia<br>\n",
    "kode_promo_1020 = [\"HEMAT10\", \"HEMAT20\", \"HIDUPMAHASISWA\", \"HIDUPFTI\"]<br>\n",
    "Membuat sebuah list yang berisi kode-kode promo yang tersedia.\n",
    "5. Mengecek syarat total belanja<br>\n",
    "syarat_total_1020 = total_1020 >= 200000<br>\n",
    "Mengecek apakah total belanja minimal Rp200.000. Hasilnya berupa True atau False.\n",
    "6. Mengecek jumlah barang<br>\n",
    "syarat_jumlah_1020 = jumlah_1021 >= 3<br>\n",
    "Mengecek apakah pelanggan membeli minimal 3 barang.\n",
    "7. Mengecek status member<br>\n",
    "status_valid_1020 = status_1020 == \"member\"<br>\n",
    "Mengecek apakah status pelanggan sama dengan \"member\". Jika sama persis, hasilnya True.\n",
    "8. Mengecek kode promo<br>\n",
    "promo_valid_1020 = promo_1020 in kode_promo_1020<br>\n",
    "Operator in digunakan untuk mengecek apakah kode promo yang dimasukkan terdapat di dalam list kode_promo_1020.\n",
    "9. Menampilkan hasil validasi<br>\n",
    "print(f\"Belanja >= Rp200000        : {syarat_total_1020}\")<br>\n",
    "print(f\"Jumlah Barang >= 3         : {syarat_jumlah_1020}\")<br>\n",
    "print(f\"Status Member              : {status_valid_1020}\")<br>\n",
    "print(f\"Kode Promo Tersedia        : {promo_valid_1020}\")<br>\n",
    "Menampilkan hasil dari setiap pemeriksaan dalam bentuk True atau False.\n",
    "10. Menentukan mendapatkan diskon<br>\n",
    "print(f\"Mendapatkan Diskon         : {syarat_jumlah_1020 or syarat_total_1020}\")<br>\n",
    "Operator or digunakan. Pelanggan dianggap mendapatkan diskon jika jumlah barang minimal 3 atau total belanja minimal Rp200.000.\n",
    "11. Menentukan mendapatkan promo<br>\n",
    "print(f\"Mendapatkan Promo          : {promo_valid_1020}\")<br>\n",
    "Menampilkan apakah kode promo yang dimasukkan tersedia.\n",
    "12. Menentukan nilai diskon<br>\n",
    "diskon_1020 = 0.05<br>\n",
    "Variabel diskon_1020 diberi nilai 0.05, yang berarti 5%.\n",
    "13. Menghitung jumlah diskon<br>\n",
    "print(f\"Diskon : Rp{diskon_1020 * total_1020}\")<br>\n",
    "Menghitung nilai diskon dengan mengalikan total belanja dengan 5%.<br>\n",
    "Contoh jika belanja Rp200.000:<br>\n",
    "0.05 × 200000 = Rp10.000\n",
    "14. Menghitung total pembayaran<br>\n",
    "print(f\"Total Pembayaran : Rp{total_1020 - total_1020 * diskon_1020}\")<br>\n",
    "Mengurangi total belanja dengan jumlah diskon untuk mendapatkan total yang harus dibayar.\n",
    "15. Menghitung rata-rata harga barang<br>\n",
    "print(f\"Rata-rata Harga Barang : Rp{(total_1020 - total_1020 * diskon_1020)/jumlah_1020}\")<br>\n",
    "Menghitung rata-rata harga setiap barang setelah diskon dengan membagi total pembayaran dengan jumlah barang.\n",
    "16. Menampilkan hak akses pelanggan<br>\n",
    "print(f\"Member Access : {status_valid_1020}\")<br>\n",
    "print(f\"Promo Access : {promo_valid_1020}\")<br>\n",
    "Menampilkan hak akses berdasarkan status member dan validitas kode promo.<br>\n",
    "Jika pelanggan adalah member, Member Access bernilai True. Jika kode promo tersedia, Promo Access bernilai True.\n",
    "17. Membuat kode transaksi<br>\n",
    "kode_transaksi_1020 = int(status_valid_1020) << 0 | int(syarat_total_1020) << 1 | int(syarat_jumlah_1020) << 2 | int<br>(promo_valid_1020) << 3\n",
    "Bagian ini mengubah nilai Boolean menjadi angka dan menyusunnya menggunakan operasi bitwise.<br>\n",
    "True dikonversi menjadi 1, sedangkan False menjadi 0.<br>\n",
    "Setiap kondisi ditempatkan pada posisi bit berbeda:<br>\n",
    "Status member → bit 0<br>\n",
    "Total belanja → bit 1<br>\n",
    "Jumlah barang → bit 2<br>\n",
    "Promo → bit 3<br>\n",
    "Operator << digunakan untuk menggeser bit, sedangkan | digunakan untuk menggabungkan semua bit tersebut.\n",
    "18. Membuat kode referensi<br>\n",
    "kode_referensi_1020 = int(status_valid_1020) << 0 | int(syarat_total_1020) << 1 | int(promo_valid_1020) << 3<br>\n",
    "Membuat kode referensi dengan menggunakan status member, total belanja, dan promo. Kondisi jumlah barang tidak dimasukkan ke dalam kode ini.\n",
    "19. Menampilkan kode biner setiap kondisi<br>\n",
    "print(f\"{format(int(status_valid_1020) << 0,\"04b\")} | {format(int(syarat_total_1020) << 1,\"04b\")} | {format(int<br>(syarat_jumlah_1020) << 2,\"04b\")} | {format(int(promo_valid_1020) << 3,\"04b\")}\")\n",
    "Menampilkan masing-masing kondisi dalam bentuk biner 4 bit.<br>\n",
    "Fungsi:<br>\n",
    "format(nilai, \"04b\")<br>\n",
    "digunakan untuk mengubah nilai menjadi biner dengan panjang minimal 4 bit.\n",
    "20. Menampilkan kode transaksi<br>\n",
    "print(f\"Kode Biner   : {format(kode_transaksi_1020,\"04b\")}\")<br>\n",
    "print(f\"Kode Desimal : {kode_transaksi_1020}\")<br>\n",
    "Menampilkan kode transaksi dalam bentuk biner dan desimal.\n",
    "21. Pemeriksaan status member<br>\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} & {format(int(status_valid_1020) << 0,\"04b\")}\")<br>\n",
    "Menampilkan operasi bitwise AND antara kode transaksi dan bit status member.<br>\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) & int(status_valid_1020) << 0,\"04b\")}\")<br>\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) & int(status_valid_1020) << 0}\")<br>\n",
    "Menghasilkan nilai berdasarkan pemeriksaan bit status member.\n",
    "22. Pemeriksaan promo<br>\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} & {format(int(promo_valid_1020) << 3,\"04b\")}\")<br>\n",
    "Menampilkan operasi AND untuk memeriksa bit promo.<br>\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) & int(promo_valid_1020) << 3,\"04b\")}\")<br>\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) & int(promo_valid_1020) << 3}\")<br>\n",
    "Menampilkan hasil pemeriksaan promo dalam bentuk biner dan desimal.\n",
    "23. Menampilkan kode transaksi dan referensi<br>\n",
    "print(f\"Kode Transaksi : {format(kode_transaksi_1020,\"04b\")}\")<br>\n",
    "print(f\"Kode Referensi : {format(kode_referensi_1020,\"04b\")}\")<br>\n",
    "Menampilkan kedua kode dalam bentuk biner 4 bit untuk dibandingkan.\n",
    "24. Membandingkan kode dengan XOR<br>\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} ^ {format(kode_referensi_1020,\"04b\")}\")<br>\n",
    "Operator ^ digunakan untuk membandingkan bit dari kode transaksi dan kode referensi. Bit yang berbeda akan menghasilkan 1.<br>\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) ^ (kode_referensi_1020),\"04b\")}\")<br>\n",
    "Baris ini menghitung XOR antara kode_transaksi_1020 dan kode_referensi_1020\n",
    "25. Pergeseran kode transaksi<br>\n",
    "print(f\"{format(kode_transaksi_1020,\"04b\")} << 1\")<br>\n",
    "Menampilkan operasi pergeseran bit kode transaksi sebanyak 1 posisi ke kiri.<br>\n",
    "print(f\"Hasil Biner   : {format((kode_transaksi_1020) << 1,\"04b\")}\")<br>\n",
    "print(f\"Hasil Desimal : {(kode_transaksi_1020) << 1}\")<br>\n",
    "Menggeser seluruh bit kode transaksi satu posisi ke kiri dan menampilkan hasilnya dalam bentuk biner dan desimal.\n",
    "26. Menampilkan tanda selesai<br>\n",
    "print(\"=== SELESAI ===\")<br>\n",
    "Menampilkan pesan bahwa program telah selesai dijalankan.\n",
    "\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a76156b2",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB III<br>KESIMPULAN</h1>\n",
    "\n",
    "Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa Python menyediakan berbagai jenis operator yang memiliki fungsi masing-masing dalam melakukan operasi terhadap nilai dan variabel, meliputi operator aritmetika, perbandingan, logika, penugasan, bitwise, keanggotaan, dan identitas. Setiap jenis operator menghasilkan keluaran yang sesuai dengan teori, baik berupa nilai numerik maupun boolean, sehingga memungkinkan programmer untuk membangun logika program yang tepat, terutama dalam percabangan dan perulangan. Melalui praktikum ini, mahasiswa tidak hanya mengenal dan memahami fungsi tiap operator, tetapi juga mampu menerapkannya dalam program sederhana serta mengetahui hasil dari setiap operasi yang dilakukan. Dengan demikian, penguasaan terhadap operator dalam Python menjadi dasar penting yang memperkuat pemahaman dasar pemrograman dan menjadi landasan untuk mempelajari konsep pemrograman yang lebih kompleks pada tahap selanjutnya.\n",
    "\n",
    "Dengan memahami berbagai operasi tersebut, mahasiswa dapat membuat program sederhana yang mampu melakukan perhitungan, membandingkan nilai, memeriksa kondisi, serta melakukan pemeriksaan terhadap data. Pemahaman mengenai operator juga menjadi salah satu dasar penting dalam mempelajari pemrograman Python lebih lanjut.\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "01a0f64e",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">DAFTAR PUSTAKA</h1>\n",
    "\n",
    "1. Python Software Foundation. The Python Tutorial – 3. The Python Tutorial. Docs.python.org. Tersedia daring: https://docs.python.org/3/tutorial/\n",
    "\n",
    "2. W3Schools. Python Operators. W3schools.com. Tersedia daring: https://www.w3schools.com/python/python_operators.asp\n",
    "\n",
    "3. Real Python. Python Operators: A Comprehensive Guide. Realpython.com. Tersedia daring: https://realpython.com/python-operators/\n",
    "\n",
    "4. Programiz. Python Operators (With Examples). Programiz.com. Tersedia daring: https://www.programiz.com/python-programming/operators\n",
    "</div>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}