{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "4f36417f",
   "metadata": {},
   "source": [
    "<h4 align=\"center\" style=\"height:1123px;font-family: 'Times New Roman'\"><b>\n",
    "\n",
    "LAPORAN PRAKTIKUM\n",
    "<br>ALGORITMA DAN PEMROGRAMAN\n",
    "<br>PERTEMUAN 4\n",
    "<br><br>\n",
    "<img src=\"https://upload.wikimedia.org/wikipedia/commons/3/3f/Logo_Universitas_Negeri_Padang.png\" width=\"180\" height=\"180\">\n",
    "<br><br>\n",
    "<strong>STRUKTUR PERCABANGAN PADA PYTHON</strong>\n",
    "<br><br><br>\n",
    "Nama : Varren Della\n",
    "<br>\n",
    "NIM : 2611531020\n",
    "<br>\n",
    "Kelas : Praktikum C\n",
    "<br>\n",
    "Dosen : Dr. Ir. Wahyudi, ST., MT dan Afdhal Dinilhak, M.Kom\n",
    "<br>\n",
    "Asisten Praktikum : Muhammad Galid Alvero\n",
    "<br><br><br>\n",
    "PROGRAM STUDI INFORMATIKA\n",
    "<br>DEPARTEMEN ELEKTRONIKA\n",
    "<br>FAKULTAS TEKNIK\n",
    "<br>UNIVERSITAS NEGERI PADANG\n",
    "<br>2026\n",
    "</b></h4>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4e92b24",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "<h1 align=\"center\">KATA PENGANTAR</h1>\n",
    "\n",
    "<p align=\"justify\">Puji syukur penulis panjatkan kepada Tuhan Yang Maha Esa karena laporan praktikum Algoritma dan Pemrograman pertemuan keempat ini dapat diselesaikan. Laporan ini disusun sebagai dokumentasi proses belajar mengenai percabangan dalam Python, mulai dari kondisi tunggal sampai pemilihan menggunakan <i>match-case</i>.</p>\n",
    "\n",
    "<p align=\"justify\">Melalui latihan ini, penulis mencoba memahami cara program mengambil keputusan berdasarkan data masukan. Selain menuliskan kode, penulis juga mencatat hasil pengujian dan alasan logis di balik setiap keluaran program.</p>\n",
    "\n",
    "<p align=\"justify\">Penulis mengucapkan terima kasih kepada dosen pengampu dan asisten praktikum, Muhammad Galid Alvero, atas arahan yang diberikan selama kegiatan praktikum. Kritik dan saran tetap diharapkan agar laporan berikutnya dapat disusun dengan lebih baik.</p>\n",
    "\n",
    "<p align=\"right\">Padang, September 2026<br><br>Varren Della</p>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "de594eee",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB I<br>PENDAHULUAN</h1>\n",
    "\n",
    "<h2>1.1 Latar Belakang</h2>\n",
    "<p align=\"justify\">Program tidak selalu menjalankan instruksi secara berurutan. Dalam banyak kasus, program perlu memilih tindakan berdasarkan keadaan tertentu. Python menyediakan percabangan <i>if</i>, <i>if-else</i>, <i>if-elif-else</i>, beberapa <i>if</i> yang berdiri sendiri, serta <i>match-case</i> untuk kebutuhan tersebut.</p>\n",
    "\n",
    "<p align=\"justify\">Pada praktikum ini, konsep percabangan diterapkan pada beberapa latihan dan sebuah studi kasus loket wahana. Studi kasus tersebut mempertemukan input pengguna, operator logika, pemeriksaan kondisi, perhitungan diskon, dan pemilihan paket dengan <i>match-case</i>.</p>\n",
    "\n",
    "<h2>1.2 Tujuan</h2>\n",
    "<ol>\n",
    "<li>Menjelaskan cara kerja percabangan dalam Python.</li>\n",
    "<li>Membedakan penggunaan <i>if</i>, <i>if-else</i>, <i>if-elif-else</i>, dan <i>match-case</i>.</li>\n",
    "<li>Menggunakan operator <i>and</i>, <i>or</i>, serta <i>!=</i> dalam pengambilan keputusan.</li>\n",
    "<li>Membangun program loket sederhana dengan perhitungan diskon kumulatif.</li>\n",
    "</ol>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b3fea9ae",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB II<br>PEMBAHASAN</h1>\n",
    "\n",
    "<h2>2.1 Percabangan pada Python</h2>\n",
    "<p align=\"justify\">Percabangan digunakan untuk menentukan blok instruksi yang dijalankan. Kondisi akan menghasilkan nilai benar atau salah, kemudian Python memilih perintah yang sesuai dengan hasil tersebut.</p>\n",
    "\n",
    "<h2>2.2 Bentuk Percabangan</h2>\n",
    "<ul>\n",
    "<li><b>If tunggal</b> dipakai ketika hanya ada satu kondisi yang perlu diperiksa.</li>\n",
    "<li><b>If-else</b> menyediakan dua jalur, yaitu saat kondisi benar dan saat kondisi tidak terpenuhi.</li>\n",
    "<li><b>If-elif-else</b> berguna untuk beberapa alternatif kondisi yang saling berurutan.</li>\n",
    "<li><b>Multi-if</b> menggunakan beberapa <i>if</i> terpisah sehingga lebih dari satu aturan dapat aktif secara bersamaan.</li>\n",
    "<li><b>Match-case</b> memilih tindakan berdasarkan pola atau nilai tertentu dan memiliki <i>case _</i> sebagai pilihan bawaan.</li>\n",
    "</ul>\n",
    "\n",
    "<h2>2.3 Studi Kasus Loket Wahana</h2>\n",
    "<p align=\"justify\">Program yang dibuat menerima data pengunjung, memilih paket wahana, memeriksa kelayakan akses, lalu menghitung harga akhir. Pada paket ATV, umur dan kepemilikan SIM C diproses menggunakan operator logika. Diskon dihitung melalui beberapa blok <i>if</i> agar setiap potongan yang memenuhi syarat dapat dijumlahkan.</p>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "7192b9ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama if1_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "\n",
    "ipk_1020 = float(input(\"Input IPK Anda = \"))\n",
    "\n",
    "if ipk_1020 > 2.75:\n",
    "    print(\"Anda Lulus Sangat Memuaskan dengan IPK\",str(ipk_1020))\n",
    "\n",
    "print(\"Program Selesai\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f504507",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan nilai IPK melalui fungsi input().\n",
    "2. Nilai IPK yang dimasukkan diubah menjadi tipe data float agar dapat digunakan sebagai nilai numerik dalam perhitungan dan perbandingan.\n",
    "3. Nilai tersebut disimpan ke dalam variabel ipk_1020.\n",
    "4. Program memeriksa kondisi menggunakan pernyataan if, yaitu apakah nilai ipk_1020 lebih besar dari 2.75.\n",
    "5. Jika kondisi tersebut benar, program menampilkan pesan “Anda Lulus Sangat Memuaskan dengan IPK” beserta nilai IPK yang dimasukkan.\n",
    "6. Jika kondisi tersebut salah, program tidak menjalankan perintah di dalam if dan langsung melanjutkan ke perintah berikutnya.\n",
    "7. Program menampilkan pesan “Program Selesai”.\n",
    "\n",
    "\n",
    "### 2.2.2 Program if2_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0ee700f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama if2_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "\n",
    "ipk_1020 = float(input(\"Input IPK Anda = \"))\n",
    "\n",
    "if ipk_1020 > 2.75:\n",
    "    print(\"Anda Lulus Sangat Memuaskan dengan IPK\",str(ipk_1020))\n",
    "else:\n",
    "    print(\"Anda Tidak Lulus\")\n",
    "print(\"Program Selesai\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dc345e00",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan nilai IPK menggunakan fungsi `input()`.\n",
    "2. Nilai IPK yang dimasukkan diubah menjadi tipe data `float` agar dapat digunakan dalam proses perbandingan.\n",
    "3. Nilai tersebut disimpan ke dalam variabel `ipk_1020`.\n",
    "4. Program memeriksa kondisi `if`, yaitu apakah nilai `ipk_1020` lebih besar dari `2.75`.\n",
    "5. Jika kondisi bernilai benar, program menampilkan pesan **“Anda Lulus Sangat Memuaskan dengan IPK”** beserta nilai IPK yang dimasukkan.\n",
    "6. Jika kondisi bernilai salah, program menjalankan bagian `else` dan menampilkan pesan **“Anda Tidak Lulus”**.\n",
    "7. Setelah proses percabangan selesai, program menampilkan pesan **“Program Selesai”**.\n",
    "\n",
    "### 2.2.3 Program multi_if1_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "4df0577a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama multi_if1_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "\n",
    "umur_1020 = int(input(\"Input Umur Anda = \"))\n",
    "sim_1020 = input(\"Apakah Anda Sudah Punya SIM (y/t): \")[0]\n",
    "\n",
    "if umur_1020 >= 17 and sim_1020 == \"y\":\n",
    "    print(\"Anda Sudah dewasa dan boleh bawa motor\")\n",
    "\n",
    "if umur_1020 >= 17 and sim_1020 != \"y\":\n",
    "    print(\"Anda Sudah dewasa tetapi tidak boleh bawa motor\")\n",
    "\n",
    "if umur_1020 < 17 and sim_1020 != \"y\":\n",
    "    print(\"Anda Belum Cukup Umur bawa motor\")\n",
    "\n",
    "if umur_1020 < 17 and sim_1020 == \"y\":\n",
    "    print(\"Anda Belum Cukup Umur punya SIM\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba3bf198",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan umur menggunakan fungsi `input()`.\n",
    "2. Nilai umur diubah menjadi tipe data `int` dan disimpan dalam variabel `umur_1020`.\n",
    "3. Program meminta pengguna memasukkan apakah sudah memiliki SIM dengan pilihan `y` atau `t`. Karakter pertama dari input diambil menggunakan `[0]` dan disimpan dalam variabel `sim_1020`.\n",
    "4. Program memeriksa kondisi pertama, yaitu `umur_1020 >= 17` dan `sim_1020 == \"y\"`. Jika kedua kondisi benar, program menampilkan bahwa pengguna sudah dewasa dan boleh membawa motor.\n",
    "5. Program memeriksa kondisi kedua, yaitu umur sudah 17 tahun atau lebih tetapi `sim_1020` bukan `\"y\"`. Jika benar, program menampilkan bahwa pengguna sudah dewasa tetapi tidak boleh membawa motor.\n",
    "6. Program memeriksa kondisi ketiga, yaitu umur kurang dari 17 tahun dan `sim_1020` bukan `\"y\"`. Jika benar, program menampilkan bahwa pengguna belum cukup umur untuk membawa motor.\n",
    "7. Program memeriksa kondisi keempat, yaitu umur kurang dari 17 tahun tetapi `sim_1020` sama dengan `\"y\"`. Jika benar, program menampilkan bahwa pengguna belum cukup umur untuk memiliki SIM.\n",
    "8. Setelah seluruh kondisi diperiksa, program selesai.\n",
    "\n",
    "### 2.2.4 Program multi_if2_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0468c84f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama multi_if2_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "# Program Menghitung Diskon Belanja\n",
    "\n",
    "# Input dan user\n",
    "total_belanja_1020 = float(input(\"Input Total Belanja (Rp): \"))\n",
    "\n",
    "# Input status member (mengecek apakah user mengetik 'y atau 't')\n",
    "input_member_1020 = input(\"Apakah Anda Member (y/t): \").strip().lower()\n",
    "is_member_1020 = input_member_1020 in [\"y\", \"t\"]\n",
    "\n",
    "# Input satus kode promo (mengecek apakah user mengetik 'y atau 't')\n",
    "input_promo_1020 = input(\"Apakah kode promo valid? (y/t): \").strip().lower()\n",
    "kode_promo_valid_1020 = input_promo_1020 in [\"y\", \"t\"]\n",
    "\n",
    "total_diskon_persen_1020 = 0\n",
    "\n",
    "# Multi-if terpisah: Setiap kondisi diperiksa secara independen\n",
    "# Diskon bisa ditumpuk (akumulasi) jika memenuhi beberapa syarat sekaligus\n",
    "\n",
    "if total_belanja_1020 > 1000000:\n",
    "    total_diskon_persen_1020 += 10  # Diskon total besar\n",
    "\n",
    "if is_member_1020:\n",
    "    total_diskon_persen_1020 += 5  # Diskon member\n",
    "\n",
    "if kode_promo_valid_1020:\n",
    "    total_diskon_persen_1020 += 15  # Diskon voucher\n",
    "\n",
    "# Menghitung nominal diskon dan total bayar\n",
    "nominal_diskon_1020 = total_belanja_1020 * (total_diskon_persen_1020 / 100)\n",
    "total_bayar_1020 = total_belanja_1020 - nominal_diskon_1020\n",
    "\n",
    "# Output hasil\n",
    "print(\"\\n--- Rincian Pembayaran ---\")\n",
    "print(f\"Total Diskon  : {total_diskon_persen_1020} (Rp {nominal_diskon_1020:.0f})\")\n",
    "print(f\"Total Bayar   : Rp {total_bayar_1020:.0f}\")\n",
    "\n",
    "print(f\"Total diskon yang Anda dapatkan: {total_diskon_persen_1020}%\")\n",
    "# Output: Total diskon yang Anda dapatkan: 30% jika belanja > 1 juta, member, dan kode promo valid"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "96da2384",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan **total belanja** dalam rupiah menggunakan fungsi `input()`.\n",
    "2. Nilai total belanja diubah menjadi tipe data `float` dan disimpan dalam variabel `total_belanja_1020`.\n",
    "3. Program meminta pengguna memasukkan status member dengan pilihan `y` atau `t`. Input kemudian diubah menjadi huruf kecil menggunakan `.lower()` dan spasi yang tidak diperlukan dihapus menggunakan `.strip()`.\n",
    "4. Program memeriksa apakah input member berupa `\"y\"` atau `\"t\"` menggunakan operator `in`. Hasil pemeriksaan disimpan dalam variabel `is_member_1020`.\n",
    "5. Program meminta pengguna memasukkan status kode promo dengan pilihan `y` atau `t`. Input diproses dengan cara yang sama dan hasilnya disimpan dalam variabel `kode_promo_valid_1020`.\n",
    "6. Variabel `total_diskon_persen_1020` diberikan nilai awal `0` sebagai tempat untuk menyimpan jumlah persentase diskon.\n",
    "7. Program memeriksa kondisi pertama. Jika total belanja lebih dari **Rp1.000.000**, program menambahkan diskon sebesar **10%**.\n",
    "8. Program memeriksa kondisi kedua. Jika pengguna merupakan member, program menambahkan diskon sebesar **5%**.\n",
    "9. Program memeriksa kondisi ketiga. Jika kode promo dianggap valid, program menambahkan diskon sebesar **15%**.\n",
    "10. Karena menggunakan beberapa `if` yang terpisah, setiap kondisi diperiksa secara independen. Jika beberapa kondisi terpenuhi, persentase diskon akan **diakumulasikan**.\n",
    "11. Program menghitung nominal diskon dengan mengalikan total belanja dengan persentase diskon yang telah diperoleh.\n",
    "12. Program menghitung total pembayaran dengan mengurangi total belanja dengan nominal diskon.\n",
    "13. Program menampilkan rincian pembayaran berupa total persentase diskon, nominal diskon dalam rupiah, dan total yang harus dibayar.\n",
    "14. Program menampilkan kembali jumlah diskon yang diperoleh dalam bentuk persentase.\n",
    "\n",
    "### 2.2.5 Program if_elif_else1_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "105d04ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama if_elif_else1_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "\n",
    "umur_1020 = int(input(\"Input Umur Anda = \"))\n",
    "sim_1020 = input(\"Apakah Anda Sudah Punya SIM (y/t): \")[0]\n",
    "\n",
    "if umur_1020 >= 17 and sim_1020 == \"y\":\n",
    "    print(\"Anda Sudah dewasa dan boleh bawa motor\")\n",
    "elif umur_1020 >= 17 and sim_1020 != \"y\":\n",
    "    print(\"Anda Sudah dewasa tetapi tidak boleh bawa motor\")\n",
    "elif umur_1020 < 17 and sim_1020 == \"y\":\n",
    "    print(\"Anda Belum Cukup Umur punya SIM\")\n",
    "else:\n",
    "    print(\"Anda Belum Cukup Umur dan tidak boleh bawa motor\")\n",
    "print(\"Program Selesai\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "033cda8c",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan umur menggunakan fungsi `input()`.\n",
    "2. Nilai umur diubah menjadi tipe data `int` dan disimpan dalam variabel `umur_1020`.\n",
    "3. Program meminta pengguna memasukkan status kepemilikan SIM dengan pilihan `y` atau `t`. Karakter pertama dari input diambil menggunakan `[0]` dan disimpan dalam variabel `sim_1020`.\n",
    "4. Program memeriksa kondisi pertama, yaitu apakah umur pengguna **17 tahun atau lebih** dan memiliki SIM (`sim_1020 == \"y\"`). Jika kondisi benar, program menampilkan bahwa pengguna sudah dewasa dan boleh membawa motor.\n",
    "5. Jika kondisi pertama salah, program memeriksa kondisi `elif` kedua, yaitu apakah umur pengguna **17 tahun atau lebih** tetapi tidak memiliki SIM. Jika benar, program menampilkan bahwa pengguna sudah dewasa tetapi tidak boleh membawa motor.\n",
    "6. Jika kondisi kedua juga salah, program memeriksa kondisi `elif` ketiga, yaitu apakah umur pengguna **kurang dari 17 tahun** tetapi memiliki SIM. Jika benar, program menampilkan bahwa pengguna belum cukup umur untuk memiliki SIM.\n",
    "7. Jika seluruh kondisi sebelumnya salah, program menjalankan bagian `else` dan menampilkan bahwa pengguna belum cukup umur dan tidak boleh membawa motor.\n",
    "8. Setelah salah satu kondisi terpenuhi, program menampilkan pesan **\"Program Selesai\"**.\n",
    "\n",
    "### 2.2.6 Program nilai_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "d6efa108",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama nilai_nim.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "# Program konversi nilai angka menjadi huruf\n",
    "\n",
    "nilai_1020 = int(input(\"Input nilai angka: \"))\n",
    "\n",
    "if nilai_1020 >= 81:\n",
    "    print(\"A\")\n",
    "elif nilai_1020 >= 70:\n",
    "    print(\"B\")\n",
    "elif nilai_1020 >= 60:\n",
    "    print(\"C\")\n",
    "elif nilai_1020 >= 50:\n",
    "    print(\"D\")\n",
    "else:\n",
    "    print(\"E\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5938716e",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan nilai angka menggunakan fungsi `input()`.\n",
    "2. Nilai yang dimasukkan diubah menjadi tipe data `int` dan disimpan dalam variabel `nilai_1020`.\n",
    "3. Program memeriksa kondisi pertama, yaitu apakah nilai **lebih besar atau sama dengan 81**. Jika benar, program menampilkan nilai **A**.\n",
    "4. Jika kondisi pertama salah, program memeriksa kondisi `elif` kedua, yaitu apakah nilai **lebih besar atau sama dengan 70**. Jika benar, program menampilkan nilai **B**.\n",
    "5. Jika kondisi kedua salah, program memeriksa kondisi `elif` ketiga, yaitu apakah nilai **lebih besar atau sama dengan 60**. Jika benar, program menampilkan nilai **C**.\n",
    "6. Jika kondisi ketiga salah, program memeriksa kondisi `elif` keempat, yaitu apakah nilai **lebih besar atau sama dengan 50**. Jika benar, program menampilkan nilai **D**.\n",
    "7. Jika seluruh kondisi sebelumnya salah, program menjalankan bagian `else` dan menampilkan nilai **E**.\n",
    "8. Setelah salah satu kondisi terpenuhi, program selesai.   \n",
    "\n",
    "### 2.2.7 Program match_case1_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "3e86bffa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buat file dengan nama case1.py\n",
    "# Buat program untuk kodisional if\n",
    "# Nama variabel ditambah 4 digit terakhir contoh: ipk_1234\n",
    "# Program ini menggunakan fungsi input()\n",
    "# Program konversi angka menjadi nama bulan\n",
    "\n",
    "bulan_1020 = int(input(\"Masukkan angka bulan (1 - 12): \"))\n",
    "\n",
    "match bulan_1020:\n",
    "    case 1:\n",
    "        print(\"Januari\")\n",
    "    case 2:\n",
    "        print(\"Februari\")\n",
    "    case 3:\n",
    "        print(\"Maret\")\n",
    "    case 4:\n",
    "        print(\"April\")\n",
    "    case 5:\n",
    "        print(\"Mei\")\n",
    "    case 6:\n",
    "        print(\"Juni\")\n",
    "    case 7:\n",
    "        print(\"Juli\")\n",
    "    case 8:\n",
    "        print(\"Agustus\")\n",
    "    case 9:\n",
    "        print(\"September\")\n",
    "    case 10:\n",
    "        print(\"Oktober\")\n",
    "    case 11:\n",
    "        print(\"November\")\n",
    "    case 12:\n",
    "        print(\"Desember\")\n",
    "    case _:\n",
    "        print(\"Angka tidak valid\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "64084288",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "Penjelasan:\n",
    "1. Program dimulai dengan meminta pengguna memasukkan angka bulan dari **1 sampai 12** menggunakan fungsi `input()`.\n",
    "2. Nilai yang dimasukkan diubah menjadi tipe data `int` dan disimpan dalam variabel `bulan_1020`.\n",
    "3. Program menggunakan struktur **`match-case`** untuk mencocokkan nilai `bulan_1020` dengan beberapa pilihan yang tersedia.\n",
    "4. Jika nilai yang dimasukkan adalah **1**, program menampilkan **Januari**.\n",
    "5. Jika nilai **2 sampai 12**, program menampilkan nama bulan yang sesuai, mulai dari Februari hingga Desember.\n",
    "6. Jika angka yang dimasukkan tidak sesuai dengan angka **1 sampai 12**, program menjalankan `case _` dan menampilkan pesan **\"Angka tidak valid\"**.\n",
    "7. Setelah nama bulan atau pesan kesalahan ditampilkan, program selesai.\n",
    "---\n",
    "## Tugas Praktikum\n",
    "\n",
    "**Soal :**\n",
    "\n",
    "<div align=\"center\">\n",
    "<img src=\"image/soal_tugas.png\" width=\"500\"><br>\n",
    "<em>Gambar 2.2 : Soal Tugas Praktikum</em>\n",
    "</div>\n",
    "\n",
    "**Kode Jawaban :**\n",
    "\n",
    "a. Kode Program tugas3_2611531020\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "3288b6ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Sistem Loket Alpro Adventure Park\n",
    "# Nama: Varren Della | Kelas: Praktikum C | NIM akhir: 1020\n",
    "\n",
    "print(\"=== SISTEM LOKET ALPRO ADVENTURE PARK ===\")\n",
    "nama_1020 = input(\"Masukkan Nama Pengunjung        : \").strip()\n",
    "umur_1020 = int(input(\"Input umur anda                 : \"))\n",
    "sim_c_1020 = input(\"Apakah Anda Sudah Punya SIM C (y/t): \")[0].strip().lower()\n",
    "\n",
    "print(\"\\nPilihan Paket Wahana (1-5):\")\n",
    "print(\"  1. Safari Rimba         (Rp 50,000)\")\n",
    "print(\"  2. Arung Jeram          (Rp 75,000)\")\n",
    "print(\"  3. Motor ATV Ekstrim    (Rp 120,000)\")\n",
    "print(\"  4. Roller Coaster Kilat (Rp 100,000)\")\n",
    "print(\"  5. All-Access VIP       (Rp 220,000)\")\n",
    "paket_1020 = int(input(\"Masukkan nomor paket (1-5)      : \"))\n",
    "jumlah_tiket_1020 = int(input(\"Masukkan jumlah tiket           : \"))\n",
    "\n",
    "if jumlah_tiket_1020 <= 0:\n",
    "    print(\"Jumlah tiket tidak valid!\")\n",
    "    exit()\n",
    "\n",
    "member_1020 = input(\"Apakah Anda member? (y/t)       : \")[0].strip().lower()\n",
    "promo_1020 = input(\"Apakah kode promo valid? (y/t)  : \")[0].strip().lower()\n",
    "\n",
    "wahana_1020 = \"\"\n",
    "harga_satuan_1020 = 0\n",
    "print(\"\\n--- KELAYAKAN PENGENDARA WAHANA ---\")\n",
    "\n",
    "match paket_1020:\n",
    "    case 1:\n",
    "        wahana_1020 = \"Wahana Safari Rimba\"\n",
    "        harga_satuan_1020 = 50000\n",
    "        if umur_1020 >= 10:\n",
    "            status_akses_1020 = \"Anda memenuhi syarat umur untuk wahana ini.\"\n",
    "        else:\n",
    "            status_akses_1020 = \"Maaf, umur Anda belum mencukupi untuk wahana ini (minimal 10 tahun).\"\n",
    "    case 2:\n",
    "        wahana_1020 = \"Wahana Arung Jeram\"\n",
    "        harga_satuan_1020 = 75000\n",
    "        if umur_1020 >= 10:\n",
    "            status_akses_1020 = \"Anda memenuhi syarat umur untuk wahana ini.\"\n",
    "        else:\n",
    "            status_akses_1020 = \"Maaf, umur Anda belum mencukupi untuk wahana ini (minimal 10 tahun).\"\n",
    "    case 3:\n",
    "        wahana_1020 = \"Wahana Motor ATV Ekstrim\"\n",
    "        harga_satuan_1020 = 120000\n",
    "        if umur_1020 >= 17 and sim_c_1020 == 'y':\n",
    "            status_akses_1020 = \"Anda sudah dewasa dan boleh mengendarai ATV sendiri.\"\n",
    "        elif umur_1020 >= 17 and sim_c_1020 != 'y':\n",
    "            status_akses_1020 = \"Anda sudah dewasa tetapi tidak boleh bawa motor ATV (wajib didampingi instruktur).\"\n",
    "        elif umur_1020 < 17 and sim_c_1020 == 'y':\n",
    "            status_akses_1020 = \"Identitas tidak valid: Belum cukup umur memiliki SIM.\"\n",
    "        else:\n",
    "            status_akses_1020 = \"Anda belum cukup umur dan tidak boleh bawa motor ATV.\"\n",
    "    case 4:\n",
    "        wahana_1020 = \"Wahana Roller Coaster Kilat\"\n",
    "        harga_satuan_1020 = 100000\n",
    "        if umur_1020 >= 10:\n",
    "            status_akses_1020 = \"Anda memenuhi syarat umur untuk wahana ini.\"\n",
    "        else:\n",
    "            status_akses_1020 = \"Maaf, umur Anda belum mencukupi untuk wahana ini (minimal 10 tahun).\"\n",
    "    case 5:\n",
    "        wahana_1020 = \"Wahana All-Access VIP\"\n",
    "        harga_satuan_1020 = 220000\n",
    "        if umur_1020 >= 10:\n",
    "            status_akses_1020 = \"Anda memenuhi syarat umur untuk wahana ini.\"\n",
    "        else:\n",
    "            status_akses_1020 = \"Maaf, umur Anda belum mencukupi untuk wahana ini (minimal 10 tahun).\"\n",
    "    case _:\n",
    "        print(\"Paket wahana tidak valid!\")\n",
    "        exit()\n",
    "\n",
    "print(f\"Status Akses: {status_akses_1020}\")\n",
    "subtotal_1020 = harga_satuan_1020 * jumlah_tiket_1020\n",
    "total_diskon_persen_1020 = 0\n",
    "\n",
    "if subtotal_1020 >= 200000:\n",
    "    total_diskon_persen_1020 += 10\n",
    "if member_1020 in [\"y\", \"ya\"]:\n",
    "    total_diskon_persen_1020 += 5\n",
    "if promo_1020 in [\"y\", \"ya\"]:\n",
    "    total_diskon_persen_1020 += 15\n",
    "if jumlah_tiket_1020 >= 5:\n",
    "    total_diskon_persen_1020 += 5\n",
    "\n",
    "nominal_diskon_1020 = subtotal_1020 * (total_diskon_persen_1020 / 100)\n",
    "total_bayar_1020 = subtotal_1020 - nominal_diskon_1020\n",
    "print(\"\\n--- Rincian Pembayaran ---\")\n",
    "print(f\"Subtotal Belanja : Rp {subtotal_1020:,.0f}\")\n",
    "print(f\"Total Diskon     : {total_diskon_persen_1020}% (Rp {nominal_diskon_1020:,.0f})\")\n",
    "print(f\"Total Bayar      : Rp {total_bayar_1020:,.0f}\")\n",
    "\n",
    "if total_bayar_1020 > 300000:\n",
    "    catatan_layanan_1020 = \"Selamat! Anda berhak mendapatkan Souvenir Gratis.\"\n",
    "else:\n",
    "    catatan_layanan_1020 = \"Terima kasih telah berkunjung.\"\n",
    "print(f\"Catatan Layanan  : {catatan_layanan_1020}\")\n",
    "print(\"Program Selesai\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4ec191f",
   "metadata": {},
   "source": [
    "<div style=\"font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "\n",
    "**Penjelasan :** \n",
    "1. Program dimulai dengan menampilkan judul **Sistem Loket Alpro Adventure Park**.\n",
    "2. Program meminta pengguna memasukkan **nama pengunjung** dan menyimpannya pada variabel `nama_1020`.\n",
    "3. Program meminta **umur pengunjung**, kemudian mengubah input menjadi tipe data `int` dan menyimpannya pada variabel `umur_1020`.\n",
    "4. Program meminta informasi kepemilikan **SIM C** dengan pilihan `y/t`. Karakter pertama dari input diambil, kemudian diubah menjadi huruf kecil dan disimpan pada `sim_c_1020`.\n",
    "5. Program menampilkan lima pilihan paket wahana beserta harga masing-masing.\n",
    "6. Pengguna memilih nomor paket wahana dan memasukkan **jumlah tiket** yang ingin dibeli.\n",
    "7. Program memeriksa jumlah tiket. Jika jumlah tiket kurang dari atau sama dengan 0, program menampilkan **\"Jumlah tiket tidak valid!\"** dan menghentikan program.\n",
    "8. Jika jumlah tiket valid, program meminta status **member** dan **kode promo** dari pengguna.\n",
    "9. Program menggunakan struktur **`match-case`** untuk menentukan paket wahana yang dipilih sekaligus melakukan pemeriksaan kelayakan berdasarkan umur dan SIM.\n",
    "10. Pada **Safari Rimba**, program memeriksa apakah umur pengunjung minimal 10 tahun. Jika memenuhi, pengunjung diperbolehkan menggunakan wahana sendiri. Jika tidak, pengunjung wajib didampingi orang tua. Harga tiket ditetapkan sebesar **Rp50.000**.\n",
    "11. Pada **Arung Jeram**, program memeriksa apakah umur pengunjung minimal 15 tahun. Jika memenuhi, pengunjung diperbolehkan menggunakan wahana sendiri. Jika tidak, pengunjung wajib didampingi orang tua. Harga tiket ditetapkan sebesar **Rp75.000**.\n",
    "12. Pada **Motor ATV Ekstrim**, program memeriksa umur dan kepemilikan SIM C menggunakan kondisi `if`, `elif`, dan `else`. Pengunjung berusia minimal 17 tahun dan memiliki SIM C diperbolehkan mengendarai ATV sendiri. Harga tiket ditetapkan sebesar **Rp120.000**.\n",
    "13. Pada **Roller Coaster Kilat**, program memeriksa apakah umur pengunjung minimal 17 tahun. Jika memenuhi, pengunjung diperbolehkan menggunakan wahana sendiri. Jika tidak, pengunjung wajib didampingi orang tua. Harga tiket ditetapkan sebesar **Rp100.000**.\n",
    "14. Pada **All-Access VIP**, program memeriksa umur dan kepemilikan SIM C. Jika berusia minimal 17 tahun dan memiliki SIM C, pengunjung diperbolehkan menggunakan semua wahana sendiri. Jika tidak memenuhi persyaratan, program memberikan keterangan sesuai kondisi yang diperiksa. Harga tiket ditetapkan sebesar **Rp220.000**.\n",
    "15. Jika nomor paket yang dimasukkan tidak sesuai dengan pilihan 1–5, program menampilkan **\"Paket wahana tidak valid!\"** dan menghentikan program.\n",
    "16. Program menetapkan nilai awal `diskon_1020` sebesar **0%**.\n",
    "17. Program memeriksa apakah total harga tiket minimal **Rp200.000**. Jika terpenuhi, diskon ditambahkan sebesar **10%**.\n",
    "18. Program memeriksa status member. Jika input berupa `y` atau `ya`, diskon ditambahkan sebesar **5%**.\n",
    "19. Program memeriksa kode promo. Jika input berupa `y` atau `ya`, diskon ditambahkan sebesar **15%**.\n",
    "20. Program memeriksa jumlah tiket. Jika jumlah tiket minimal **5**, diskon ditambahkan sebesar **5%**.\n",
    "21. Karena menggunakan beberapa `if` secara terpisah, setiap diskon dapat **diakumulasikan** apabila beberapa kondisi terpenuhi.\n",
    "22. Program menghitung **subtotal belanja** dengan mengalikan harga satuan tiket dengan jumlah tiket.\n",
    "23. Program menghitung **nominal diskon** berdasarkan persentase diskon yang telah diperoleh.\n",
    "24. Program menghitung **total pembayaran** dengan mengurangi subtotal belanja dengan nominal diskon.\n",
    "25. Program menampilkan rincian pembayaran berupa subtotal belanja, total diskon, dan total pembayaran.\n",
    "26. Program memeriksa apakah subtotal belanja lebih dari **Rp300.000**. Jika terpenuhi, program menampilkan informasi bahwa pengunjung mendapatkan **souvenir gratis**.\n",
    "27. Program menampilkan catatan layanan berupa ucapan terima kasih kepada pengunjung.\n",
    "28. Program menampilkan pesan **\"Program Selesai\"** dan program berakhir.\n",
    "\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a76156b2",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">BAB III<br>KESIMPULAN</h1>\n",
    "\n",
    "<p align=\"justify\">Percabangan merupakan bagian penting dalam penyusunan algoritma karena memungkinkan program merespons kondisi yang berbeda. Setiap bentuk percabangan memiliki kegunaan tersendiri: <i>if</i> untuk pemeriksaan sederhana, <i>if-else</i> untuk dua pilihan, <i>if-elif-else</i> untuk beberapa alternatif, dan <i>match-case</i> untuk pencocokan nilai.</p>\n",
    "\n",
    "<p align=\"justify\">Berdasarkan studi kasus loket, penggunaan beberapa <i>if</i> terpisah dapat menghasilkan diskon akumulatif, sedangkan operator logika membantu membuat validasi yang lebih spesifik. Program juga dapat menghasilkan rincian pembayaran secara otomatis setelah seluruh kondisi diproses.</p>\n",
    "\n",
    "<p align=\"justify\">Dengan demikian, latihan ini membantu penulis memahami hubungan antara input, kondisi, proses perhitungan, dan keluaran program. Pengujian dengan beberapa kombinasi data tetap diperlukan agar setiap cabang dapat dipastikan berjalan sesuai tujuan.</p>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "01a0f64e",
   "metadata": {},
   "source": [
    "---\n",
    "<div style=\"height:1123px;font-family: 'Times New Roman', Times, serif;font-size: 18px;\">\n",
    "<h1 align=\"center\">DAFTAR PUSTAKA</h1>\n",
    "\n",
    "<ol>\n",
    "<li>Python Software Foundation. 2026. <i>Python 3 Documentation: Compound Statements</i>. Diakses September 2026.</li>\n",
    "<li>Python Software Foundation. 2026. <i>Python 3 Documentation: match Statement</i>. Diakses September 2026.</li>\n",
    "<li>Wahyudi dan Afdhal Dinilhak. 2026. <i>Modul Praktikum Algoritma dan Pemrograman: Struktur Percabangan</i>. Padang: Program Studi Informatika.</li>\n",
    "<li>Downey, Allen B. 2015. <i>Think Python: How to Think Like a Computer Scientist</i>. O'Reilly Media.</li>\n",
    "</ol>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7d897505",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}